// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: admin_requests.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const approveAdminRequest = `-- name: ApproveAdminRequest :exec
UPDATE admin_requests
SET status = 'APPROVED', updated_at = now()
WHERE id = $1 AND status = 'PENDING'
`

func (q *Queries) ApproveAdminRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, approveAdminRequest, id)
	return err
}

const createAdminRequest = `-- name: CreateAdminRequest :exec
INSERT INTO admin_requests ( user_id, reason)
VALUES ($1, $2)
`

type CreateAdminRequestParams struct {
	UserID uuid.UUID
	Reason string
}

func (q *Queries) CreateAdminRequest(ctx context.Context, arg CreateAdminRequestParams) error {
	_, err := q.db.ExecContext(ctx, createAdminRequest, arg.UserID, arg.Reason)
	return err
}

const getAdminRequestByID = `-- name: GetAdminRequestByID :one
SELECT id, user_id, reason, status, created_at, updated_at
FROM admin_requests
WHERE id = $1
`

func (q *Queries) GetAdminRequestByID(ctx context.Context, id uuid.UUID) (AdminRequest, error) {
	row := q.db.QueryRowContext(ctx, getAdminRequestByID, id)
	var i AdminRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminRequestsByUserID = `-- name: GetAdminRequestsByUserID :many
SELECT id, user_id, reason, status, created_at, updated_at
FROM admin_requests
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAdminRequestsByUserID(ctx context.Context, userID uuid.UUID) ([]AdminRequest, error) {
	rows, err := q.db.QueryContext(ctx, getAdminRequestsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminRequest
	for rows.Next() {
		var i AdminRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingAdminRequests = `-- name: GetPendingAdminRequests :many
SELECT id, user_id, reason, status, created_at, updated_at
FROM admin_requests
WHERE status = 'PENDING'
ORDER BY created_at
`

func (q *Queries) GetPendingAdminRequests(ctx context.Context) ([]AdminRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingAdminRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminRequest
	for rows.Next() {
		var i AdminRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectAdminRequest = `-- name: RejectAdminRequest :exec
UPDATE admin_requests
SET status = 'REJECTED', updated_at = now()
WHERE id = $1 AND status = 'PENDING'
`

func (q *Queries) RejectAdminRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, rejectAdminRequest, id)
	return err
}
