// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cart.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const calculateCartTotal = `-- name: CalculateCartTotal :one
SELECT SUM(quantity * price) AS total_price
FROM cart_items
WHERE shopping_cart_id = $1
`

// Calculate the total price of items in the cart
func (q *Queries) CalculateCartTotal(ctx context.Context, shoppingCartID uuid.NullUUID) (int64, error) {
	row := q.queryRow(ctx, q.calculateCartTotalStmt, calculateCartTotal, shoppingCartID)
	var total_price int64
	err := row.Scan(&total_price)
	return total_price, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE shopping_cart_id = $1
`

// Remove all items from the cart
func (q *Queries) ClearCart(ctx context.Context, shoppingCartID uuid.NullUUID) error {
	_, err := q.exec(ctx, q.clearCartStmt, clearCart, shoppingCartID)
	return err
}

const getAllCartItems = `-- name: GetAllCartItems :many
SELECT id, shopping_cart_id, product_id, quantity, price, created_at, updated_at
FROM cart_items
WHERE shopping_cart_id = $1
`

type GetAllCartItemsRow struct {
	ID             uuid.UUID
	ShoppingCartID uuid.NullUUID
	ProductID      uuid.NullUUID
	Quantity       int32
	Price          string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

// Get all items in the cart
func (q *Queries) GetAllCartItems(ctx context.Context, shoppingCartID uuid.NullUUID) ([]GetAllCartItemsRow, error) {
	rows, err := q.query(ctx, q.getAllCartItemsStmt, getAllCartItems, shoppingCartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCartItemsRow{}
	for rows.Next() {
		var i GetAllCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingCartID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, quantity FROM cart_items
WHERE shopping_cart_id = $1 AND product_id = $2
`

type GetCartItemParams struct {
	ShoppingCartID uuid.NullUUID
	ProductID      uuid.NullUUID
}

type GetCartItemRow struct {
	ID       uuid.UUID
	Quantity int32
}

// Get a cart item
func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (GetCartItemRow, error) {
	row := q.queryRow(ctx, q.getCartItemStmt, getCartItem, arg.ShoppingCartID, arg.ProductID)
	var i GetCartItemRow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE shopping_cart_id = $1 AND product_id = $2
`

type RemoveCartItemParams struct {
	ShoppingCartID uuid.NullUUID
	ProductID      uuid.NullUUID
}

// Remove an item from the cart
func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.exec(ctx, q.removeCartItemStmt, removeCartItem, arg.ShoppingCartID, arg.ProductID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
UPDATE cart_items
SET quantity = $3, updated_at = NOW()
WHERE shopping_cart_id = $1 AND product_id = $2
`

type UpdateCartItemQuantityParams struct {
	ShoppingCartID uuid.NullUUID
	ProductID      uuid.NullUUID
	Quantity       int32
}

// Update the quantity of an item in the cart
func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.exec(ctx, q.updateCartItemQuantityStmt, updateCartItemQuantity, arg.ShoppingCartID, arg.ProductID, arg.Quantity)
	return err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (id, shopping_cart_id, product_id, quantity, price, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (shopping_cart_id, product_id)
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity
RETURNING id, shopping_cart_id, product_id, quantity, price, created_at, updated_at
`

type UpsertCartItemParams struct {
	ShoppingCartID uuid.NullUUID
	ProductID      uuid.NullUUID
	Quantity       int32
	Price          string
}

type UpsertCartItemRow struct {
	ID             uuid.UUID
	ShoppingCartID uuid.NullUUID
	ProductID      uuid.NullUUID
	Quantity       int32
	Price          string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

// Insert or update the item in the cart
func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (UpsertCartItemRow, error) {
	row := q.queryRow(ctx, q.upsertCartItemStmt, upsertCartItem,
		arg.ShoppingCartID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i UpsertCartItemRow
	err := row.Scan(
		&i.ID,
		&i.ShoppingCartID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
