// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cart.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const calculateCartTotal = `-- name: CalculateCartTotal :one
SELECT SUM(quantity * price) AS total_price
FROM cart_items
WHERE shopping_cart_id = $1
`

// Calculate the total price of items in the cart
func (q *Queries) CalculateCartTotal(ctx context.Context, shoppingCartID uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.calculateCartTotalStmt, calculateCartTotal, shoppingCartID)
	var total_price int64
	err := row.Scan(&total_price)
	return total_price, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE shopping_cart_id = $1
`

// Remove all items from the cart
func (q *Queries) ClearCart(ctx context.Context, shoppingCartID uuid.UUID) error {
	_, err := q.exec(ctx, q.clearCartStmt, clearCart, shoppingCartID)
	return err
}

const getAllCartItems = `-- name: GetAllCartItems :many
SELECT
    ci.id,
    ci.product_id,
    p.name,
    p.description,
    ci.quantity,
    ci.price,
    pi.image_url
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
LEFT JOIN product_images pi ON p.id = pi.product_id AND (pi.position = 1 OR pi.position IS NULL)
WHERE ci.shopping_cart_id = $1
GROUP BY ci.id, p.id, pi.image_url
ORDER BY ci.created_at ASC
`

type GetAllCartItemsRow struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	Name        string
	Description sql.NullString
	Quantity    int32
	Price       string
	ImageUrl    sql.NullString
}

// Get all items in the cart
func (q *Queries) GetAllCartItems(ctx context.Context, shoppingCartID uuid.UUID) ([]GetAllCartItemsRow, error) {
	rows, err := q.query(ctx, q.getAllCartItemsStmt, getAllCartItems, shoppingCartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCartItemsRow{}
	for rows.Next() {
		var i GetAllCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Price,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItem = `-- name: GetCartItem :one
SELECT
    ci.id,
    ci.product_id,
    p.name,
    p.description,
    ci.quantity,
    ci.price,
    pi.image_url
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
LEFT JOIN product_images pi ON p.id = pi.product_id AND (pi.position = 1 OR pi.position IS NULL)
WHERE ci.shopping_cart_id = $1 AND ci.product_id = $2
LIMIT 1
`

type GetCartItemParams struct {
	ShoppingCartID uuid.UUID
	ProductID      uuid.UUID
}

type GetCartItemRow struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	Name        string
	Description sql.NullString
	Quantity    int32
	Price       string
	ImageUrl    sql.NullString
}

// Get a cart item
func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (GetCartItemRow, error) {
	row := q.queryRow(ctx, q.getCartItemStmt, getCartItem, arg.ShoppingCartID, arg.ProductID)
	var i GetCartItemRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Price,
		&i.ImageUrl,
	)
	return i, err
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE shopping_cart_id = $1 AND product_id = $2
`

type RemoveCartItemParams struct {
	ShoppingCartID uuid.UUID
	ProductID      uuid.UUID
}

// Remove an item from the cart
func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.exec(ctx, q.removeCartItemStmt, removeCartItem, arg.ShoppingCartID, arg.ProductID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
UPDATE cart_items
SET quantity = $3, updated_at = NOW()
WHERE shopping_cart_id = $1 AND product_id = $2
`

type UpdateCartItemQuantityParams struct {
	ShoppingCartID uuid.UUID
	ProductID      uuid.UUID
	Quantity       int32
}

// Update the quantity of an item in the cart
func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.exec(ctx, q.updateCartItemQuantityStmt, updateCartItemQuantity, arg.ShoppingCartID, arg.ProductID, arg.Quantity)
	return err
}

const updateCartUserID = `-- name: UpdateCartUserID :exec
UPDATE shopping_carts
SET user_id = $2
WHERE id = $1
`

type UpdateCartUserIDParams struct {
	ID     uuid.UUID
	UserID uuid.NullUUID
}

func (q *Queries) UpdateCartUserID(ctx context.Context, arg UpdateCartUserIDParams) error {
	_, err := q.exec(ctx, q.updateCartUserIDStmt, updateCartUserID, arg.ID, arg.UserID)
	return err
}

const upsertCartItem = `-- name: UpsertCartItem :one
WITH upserted AS (
    INSERT INTO cart_items (id, shopping_cart_id, product_id, quantity, price, created_at, updated_at)
    VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW(), NOW())
    ON CONFLICT (shopping_cart_id, product_id)
    DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity, updated_at = NOW()
    RETURNING id, shopping_cart_id, product_id, quantity, price, created_at, updated_at
)
SELECT
    upserted.id,
    upserted.product_id,
    products.name,
    products.description,
    upserted.quantity,
    upserted.price,
    product_images.image_url
FROM upserted
JOIN products ON upserted.product_id = products.id
LEFT JOIN product_images ON products.id = product_images.product_id
WHERE product_images.position = 1 OR product_images.position IS NULL
LIMIT 1
`

type UpsertCartItemParams struct {
	ShoppingCartID uuid.UUID
	ProductID      uuid.UUID
	Quantity       int32
	Price          string
}

type UpsertCartItemRow struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	Name        string
	Description sql.NullString
	Quantity    int32
	Price       string
	ImageUrl    sql.NullString
}

// Insert or update the item in the cart
func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (UpsertCartItemRow, error) {
	row := q.queryRow(ctx, q.upsertCartItemStmt, upsertCartItem,
		arg.ShoppingCartID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i UpsertCartItemRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Price,
		&i.ImageUrl,
	)
	return i, err
}
