// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: categories.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkCategoryExistence = `-- name: CheckCategoryExistence :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE id = $1
) AS exists
`

func (q *Queries) CheckCategoryExistence(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkCategoryExistence, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, parent_id)
VALUES ($1, $2)
    RETURNING id, name, parent_id, created_at, updated_at, is_active, position
`

type CreateCategoryParams struct {
	Name     string
	ParentID uuid.NullUUID
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Position,
	)
	return i, err
}

const getCategoriesByParentID = `-- name: GetCategoriesByParentID :many
SELECT id, name, parent_id, created_at, updated_at, is_active, position
FROM categories
WHERE parent_id = $1
ORDER BY name
`

func (q *Queries) GetCategoriesByParentID(ctx context.Context, parentID uuid.NullUUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesWithProductsCount = `-- name: GetCategoriesWithProductsCount :many
SELECT c.id, c.name, c.parent_id, c.position, c.created_at, c.updated_at, c.is_active,COUNT(p.id) as products_count
FROM categories c
         LEFT JOIN products p ON c.id = p.category_id
GROUP BY c.id
ORDER BY c.name
`

type GetCategoriesWithProductsCountRow struct {
	ID            uuid.UUID
	Name          string
	ParentID      uuid.NullUUID
	Position      int32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	IsActive      bool
	ProductsCount int64
}

func (q *Queries) GetCategoriesWithProductsCount(ctx context.Context) ([]GetCategoriesWithProductsCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesWithProductsCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesWithProductsCountRow
	for rows.Next() {
		var i GetCategoriesWithProductsCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.ProductsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesWithSubcategoryCount = `-- name: GetCategoriesWithSubcategoryCount :many
SELECT c.id, c.name, c.parent_id, c.created_at, c.position ,c.updated_at, c.is_active,COUNT(sc.id) as subcategory_count
FROM categories c
         LEFT JOIN categories sc ON c.id = sc.parent_id
GROUP BY c.id
ORDER BY c.name
`

type GetCategoriesWithSubcategoryCountRow struct {
	ID               uuid.UUID
	Name             string
	ParentID         uuid.NullUUID
	CreatedAt        sql.NullTime
	Position         int32
	UpdatedAt        sql.NullTime
	IsActive         bool
	SubcategoryCount int64
}

func (q *Queries) GetCategoriesWithSubcategoryCount(ctx context.Context) ([]GetCategoriesWithSubcategoryCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesWithSubcategoryCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesWithSubcategoryCountRow
	for rows.Next() {
		var i GetCategoriesWithSubcategoryCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.Position,
			&i.UpdatedAt,
			&i.IsActive,
			&i.SubcategoryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, parent_id, created_at, updated_at, is_active, position
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Position,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, parent_id, created_at, updated_at, is_active, position
FROM categories
WHERE name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Position,
	)
	return i, err
}

const getCategoryTree = `-- name: GetCategoryTree :many
WITH RECURSIVE category_tree AS (
    SELECT id, name, parent_id, created_at, updated_at, is_active, position
    FROM categories
    WHERE parent_id IS NULL
    UNION
    SELECT c.id, c.name, c.parent_id, c.created_at, c.updated_at, c.is_active
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
)
SELECT id, name, parent_id, created_at, updated_at, is_active, position
FROM category_tree
ORDER BY parent_id, name
`

type GetCategoryTreeRow struct {
	ID        uuid.UUID
	Name      string
	ParentID  uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	IsActive  bool
	Position  int32
}

func (q *Queries) GetCategoryTree(ctx context.Context) ([]GetCategoryTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryTreeRow
	for rows.Next() {
		var i GetCategoryTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentCategories = `-- name: GetParentCategories :many
SELECT id, name, parent_id, created_at, updated_at, is_active, position
FROM categories
WHERE parent_id IS NULL
ORDER BY name
`

func (q *Queries) GetParentCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getParentCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, parent_id, created_at, updated_at, is_active, position
FROM categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteCategory, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, parent_id = $3, position = $4, updated_at = NOW()
WHERE id = $1
    RETURNING id, name, parent_id, created_at, updated_at, is_active, position
`

type UpdateCategoryParams struct {
	ID       uuid.UUID
	Name     string
	ParentID uuid.NullUUID
	Position int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Position,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Position,
	)
	return i, err
}
