// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: filter_products.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countAllProductsByFilters = `-- name: CountAllProductsByFilters :one
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
    WHERE
        c.name = ANY($1::VARCHAR[]) OR $1 IS NULL

    UNION ALL

    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
            JOIN
        category_hierarchy ch ON c.parent_id = ch.id
),
               rate AS (
                   SELECT COALESCE(
                                  (SELECT rate_to_kes
                                   FROM exchange_rates
                                   WHERE currency_code = 'USD'
                                     AND (valid_to IS NULL OR valid_to >= NOW())
                                     AND valid_from <= NOW()
                                   ORDER BY valid_from DESC
                                   LIMIT 1),
                                  135) AS rate_to_kes
               ),
               filtered_products AS (
                   SELECT
                       p.id
                   FROM
                       products p
                   WHERE
                       (p.category_id IN (SELECT id FROM category_hierarchy) OR $1 IS NULL)
                     AND (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric BETWEEN $2 AND $3
                     AND p.status = 'active'
               ),
               filtered_attributes AS (
                   SELECT
                       ptav.product_id
                   FROM
                       product_to_attribute_values ptav
                           JOIN
                       product_attribute_values pav ON ptav.attribute_value_id = pav.id
                           JOIN
                       product_attributes pa ON pav.attribute_id = pa.id
                   WHERE
                       ptav.product_id IN (SELECT id FROM filtered_products)
                     AND (
                       jsonb_typeof($4::jsonb) IS NULL
                           OR EXISTS (
                           SELECT 1
                           FROM jsonb_each_text($4::jsonb) AS filter(attr_name, attr_value)
                           WHERE pa.name = filter.attr_name
                             AND pav.value = filter.attr_value
                       )
                       )
                   GROUP BY
                       ptav.product_id
                   HAVING
                       COUNT(DISTINCT pa.name) = (SELECT COUNT(*) FROM jsonb_each_text($4::jsonb))
               )
SELECT
    COUNT(DISTINCT fa.product_id) AS total_products
FROM
    filtered_attributes fa
`

type CountAllProductsByFiltersParams struct {
	Column1    []string
	UsdPrice   string
	UsdPrice_2 string
	Column4    json.RawMessage
}

func (q *Queries) CountAllProductsByFilters(ctx context.Context, arg CountAllProductsByFiltersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllProductsByFilters,
		pq.Array(arg.Column1),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column4,
	)
	var total_products int64
	err := row.Scan(&total_products)
	return total_products, err
}

const getAllProductsByFiltersNameAsc = `-- name: GetAllProductsByFiltersNameAsc :many
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
    WHERE
        c.name = ANY($1::VARCHAR[]) OR $1 IS NULL

    UNION ALL

    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
            JOIN
        category_hierarchy ch ON c.parent_id = ch.id
),
               rate AS (
                   SELECT COALESCE(
                                  (SELECT rate_to_kes
                                   FROM exchange_rates
                                   WHERE currency_code = 'USD'
                                     AND (valid_to IS NULL OR valid_to >= NOW())
                                     AND valid_from <= NOW()
                                   ORDER BY valid_from DESC
                                   LIMIT 1),
                                  135) AS rate_to_kes
               ),
               filtered_products AS (
                   SELECT
                       p.id,
                       p.name,
                       p.description,
                       (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric AS price_in_kes,
                       p.slug,
                       COALESCE(
                               (SELECT MAX(d.discount_percentage)
                                FROM discounts d
                                WHERE d.product_id = p.id
                                  AND d.start_date <= NOW()
                                  AND (d.end_date IS NULL OR d.end_date >= NOW())
                               ), 0)::numeric AS discount_percent,
                       (SELECT pi.image_url
                        FROM product_images pi
                        WHERE pi.product_id = p.id
                        ORDER BY pi.position ASC
                        LIMIT 1) AS image_url
                   FROM
                       products p
                   WHERE
                       (p.category_id IN (SELECT id FROM category_hierarchy) OR $1 IS NULL)
                     AND (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric BETWEEN $2 AND $3
                     AND p.status = 'active'
               ),
               filtered_attributes AS (
                   SELECT
                       ptav.product_id
                   FROM
                       product_to_attribute_values ptav
                           JOIN
                       product_attribute_values pav ON ptav.attribute_value_id = pav.id
                           JOIN
                       product_attributes pa ON pav.attribute_id = pa.id
                   WHERE
                       ptav.product_id IN (SELECT id FROM filtered_products)
                     AND (
                       jsonb_typeof($4::jsonb) IS NULL
                           OR EXISTS (
                           SELECT 1
                           FROM jsonb_each_text($4::jsonb) AS filter(attr_name, attr_value)
                           WHERE pa.name = filter.attr_name
                             AND pav.value = filter.attr_value
                       )
                       )
                   GROUP BY
                       ptav.product_id
                   HAVING
                       COUNT(DISTINCT pa.name) = (SELECT COUNT(*) FROM jsonb_each_text($4::jsonb))
               ),
               final_products AS (
                   SELECT DISTINCT
                       fp.id, fp.name, fp.description, fp.price_in_kes, fp.slug, fp.discount_percent, fp.image_url
                   FROM
                       filtered_products fp
                           JOIN
                       filtered_attributes fa ON fp.id = fa.product_id
               )
SELECT
    fp.id,
    fp.name,
    fp.description,
    fp.price_in_kes AS price,
    fp.image_url AS imageURL,
    fp.discount_percent AS discountPercent,
    fp.slug
FROM
    final_products fp
ORDER BY
    fp.name ASC
LIMIT
    $5 OFFSET $6
`

type GetAllProductsByFiltersNameAscParams struct {
	Column1    []string
	UsdPrice   string
	UsdPrice_2 string
	Column4    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetAllProductsByFiltersNameAscRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Imageurl        string
	Discountpercent string
	Slug            string
}

func (q *Queries) GetAllProductsByFiltersNameAsc(ctx context.Context, arg GetAllProductsByFiltersNameAscParams) ([]GetAllProductsByFiltersNameAscRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsByFiltersNameAsc,
		pq.Array(arg.Column1),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsByFiltersNameAscRow
	for rows.Next() {
		var i GetAllProductsByFiltersNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Imageurl,
			&i.Discountpercent,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProductsByFiltersNameDesc = `-- name: GetAllProductsByFiltersNameDesc :many
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
    WHERE
        c.name = ANY($1::VARCHAR[]) OR $1 IS NULL

    UNION ALL

    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
            JOIN
        category_hierarchy ch ON c.parent_id = ch.id
),
               rate AS (
                   SELECT COALESCE(
                                  (SELECT rate_to_kes
                                   FROM exchange_rates
                                   WHERE currency_code = 'USD'
                                     AND (valid_to IS NULL OR valid_to >= NOW())
                                     AND valid_from <= NOW()
                                   ORDER BY valid_from DESC
                                   LIMIT 1),
                                  135) AS rate_to_kes
               ),
               filtered_products AS (
                   SELECT
                       p.id,
                       p.name,
                       p.description,
                       (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric AS price_in_kes,
                       p.slug,
                       COALESCE(
                               (SELECT MAX(d.discount_percentage)
                                FROM discounts d
                                WHERE d.product_id = p.id
                                  AND d.start_date <= NOW()
                                  AND (d.end_date IS NULL OR d.end_date >= NOW())
                               ), 0)::numeric AS discount_percent,
                       (SELECT pi.image_url
                        FROM product_images pi
                        WHERE pi.product_id = p.id
                        ORDER BY pi.position ASC
                        LIMIT 1) AS image_url
                   FROM
                       products p
                   WHERE
                       (p.category_id IN (SELECT id FROM category_hierarchy) OR $1 IS NULL)
                     AND (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric BETWEEN $2 AND $3
                     AND p.status = 'active'
               ),
               filtered_attributes AS (
                   SELECT
                       ptav.product_id
                   FROM
                       product_to_attribute_values ptav
                           JOIN
                       product_attribute_values pav ON ptav.attribute_value_id = pav.id
                           JOIN
                       product_attributes pa ON pav.attribute_id = pa.id
                   WHERE
                       ptav.product_id IN (SELECT id FROM filtered_products)
                     AND (
                       jsonb_typeof($4::jsonb) IS NULL
                           OR EXISTS (
                           SELECT 1
                           FROM jsonb_each_text($4::jsonb) AS filter(attr_name, attr_value)
                           WHERE pa.name = filter.attr_name
                             AND pav.value = filter.attr_value
                       )
                       )
                   GROUP BY
                       ptav.product_id
                   HAVING
                       COUNT(DISTINCT pa.name) = (SELECT COUNT(*) FROM jsonb_each_text($4::jsonb))
               ),
               final_products AS (
                   SELECT DISTINCT
                       fp.id, fp.name, fp.description, fp.price_in_kes, fp.slug, fp.discount_percent, fp.image_url
                   FROM
                       filtered_products fp
                           JOIN
                       filtered_attributes fa ON fp.id = fa.product_id
               )
SELECT
    fp.id,
    fp.name,
    fp.description,
    fp.price_in_kes AS price,
    fp.image_url AS imageURL,
    fp.discount_percent AS discountPercent,
    fp.slug
FROM
    final_products fp
ORDER BY
    fp.name DESC
LIMIT
    $5 OFFSET $6
`

type GetAllProductsByFiltersNameDescParams struct {
	Column1    []string
	UsdPrice   string
	UsdPrice_2 string
	Column4    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetAllProductsByFiltersNameDescRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Imageurl        string
	Discountpercent string
	Slug            string
}

func (q *Queries) GetAllProductsByFiltersNameDesc(ctx context.Context, arg GetAllProductsByFiltersNameDescParams) ([]GetAllProductsByFiltersNameDescRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsByFiltersNameDesc,
		pq.Array(arg.Column1),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsByFiltersNameDescRow
	for rows.Next() {
		var i GetAllProductsByFiltersNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Imageurl,
			&i.Discountpercent,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProductsByFiltersNewest = `-- name: GetAllProductsByFiltersNewest :many
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
    WHERE
        c.name = ANY($1::VARCHAR[]) OR $1 IS NULL

    UNION ALL

    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
            JOIN
        category_hierarchy ch ON c.parent_id = ch.id
),
               rate AS (
                   SELECT COALESCE(
                                  (SELECT rate_to_kes
                                   FROM exchange_rates
                                   WHERE currency_code = 'USD'
                                     AND (valid_to IS NULL OR valid_to >= NOW())
                                     AND valid_from <= NOW()
                                   ORDER BY valid_from DESC
                                   LIMIT 1),
                                  135) AS rate_to_kes
               ),
               filtered_products AS (
                   SELECT
                       p.id,
                       p.name,
                       p.description,
                       (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric AS price_in_kes,
                       p.slug,
                       COALESCE(
                               (SELECT MAX(d.discount_percentage)
                                FROM discounts d
                                WHERE d.product_id = p.id
                                  AND d.start_date <= NOW()
                                  AND (d.end_date IS NULL OR d.end_date >= NOW())
                               ), 0)::numeric AS discount_percent,
                       (SELECT pi.image_url
                        FROM product_images pi
                        WHERE pi.product_id = p.id
                        ORDER BY pi.position ASC
                        LIMIT 1) AS image_url,
                       p.created_at
                   FROM
                       products p
                   WHERE
                       (p.category_id IN (SELECT id FROM category_hierarchy) OR $1 IS NULL)
                     AND (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric BETWEEN $2 AND $3
                     AND p.status = 'active'
               ),
               filtered_attributes AS (
                   SELECT
                       ptav.product_id
                   FROM
                       product_to_attribute_values ptav
                           JOIN
                       product_attribute_values pav ON ptav.attribute_value_id = pav.id
                           JOIN
                       product_attributes pa ON pav.attribute_id = pa.id
                   WHERE
                       ptav.product_id IN (SELECT id FROM filtered_products)
                     AND (
                       jsonb_typeof($4::jsonb) IS NULL
                           OR EXISTS (
                           SELECT 1
                           FROM jsonb_each_text($4::jsonb) AS filter(attr_name, attr_value)
                           WHERE pa.name = filter.attr_name
                             AND pav.value = filter.attr_value
                       )
                       )
                   GROUP BY
                       ptav.product_id
                   HAVING
                       COUNT(DISTINCT pa.name) = (SELECT COUNT(*) FROM jsonb_each_text($4::jsonb))
               ),
               final_products AS (
                   SELECT DISTINCT
                       fp.id, fp.name, fp.description, fp.price_in_kes, fp.slug, fp.discount_percent, fp.image_url, fp.created_at
                   FROM
                       filtered_products fp
                           JOIN
                       filtered_attributes fa ON fp.id = fa.product_id
               )
SELECT
    fp.id,
    fp.name,
    fp.description,
    fp.price_in_kes AS price,
    fp.image_url AS imageURL,
    fp.discount_percent AS discountPercent,
    fp.slug,
    fp.created_at
FROM
    final_products fp
ORDER BY
    fp.created_at DESC
LIMIT
    $5 OFFSET $6
`

type GetAllProductsByFiltersNewestParams struct {
	Column1    []string
	UsdPrice   string
	UsdPrice_2 string
	Column4    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetAllProductsByFiltersNewestRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Imageurl        string
	Discountpercent string
	Slug            string
	CreatedAt       sql.NullTime
}

func (q *Queries) GetAllProductsByFiltersNewest(ctx context.Context, arg GetAllProductsByFiltersNewestParams) ([]GetAllProductsByFiltersNewestRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsByFiltersNewest,
		pq.Array(arg.Column1),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsByFiltersNewestRow
	for rows.Next() {
		var i GetAllProductsByFiltersNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Imageurl,
			&i.Discountpercent,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProductsByFiltersOldest = `-- name: GetAllProductsByFiltersOldest :many
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
    WHERE
        c.name = ANY($1::VARCHAR[]) OR $1 IS NULL

    UNION ALL

    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
            JOIN
        category_hierarchy ch ON c.parent_id = ch.id
),
               rate AS (
                   SELECT COALESCE(
                                  (SELECT rate_to_kes
                                   FROM exchange_rates
                                   WHERE currency_code = 'USD'
                                     AND (valid_to IS NULL OR valid_to >= NOW())
                                     AND valid_from <= NOW()
                                   ORDER BY valid_from DESC
                                   LIMIT 1),
                                  135) AS rate_to_kes
               ),
               filtered_products AS (
                   SELECT
                       p.id,
                       p.name,
                       p.description,
                       (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric AS price_in_kes,
                       p.slug,
                       COALESCE(
                               (SELECT MAX(d.discount_percentage)
                                FROM discounts d
                                WHERE d.product_id = p.id
                                  AND d.start_date <= NOW()
                                  AND (d.end_date IS NULL OR d.end_date >= NOW())
                               ), 0)::numeric AS discount_percent,
                       (SELECT pi.image_url
                        FROM product_images pi
                        WHERE pi.product_id = p.id
                        ORDER BY pi.position ASC
                        LIMIT 1) AS image_url,
                       p.created_at
                   FROM
                       products p
                   WHERE
                       (p.category_id IN (SELECT id FROM category_hierarchy) OR $1 IS NULL)
                     AND (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric BETWEEN $2 AND $3
                     AND p.status = 'active'
               ),
               filtered_attributes AS (
                   SELECT
                       ptav.product_id
                   FROM
                       product_to_attribute_values ptav
                           JOIN
                       product_attribute_values pav ON ptav.attribute_value_id = pav.id
                           JOIN
                       product_attributes pa ON pav.attribute_id = pa.id
                   WHERE
                       ptav.product_id IN (SELECT id FROM filtered_products)
                     AND (
                       jsonb_typeof($4::jsonb) IS NULL
                           OR EXISTS (
                           SELECT 1
                           FROM jsonb_each_text($4::jsonb) AS filter(attr_name, attr_value)
                           WHERE pa.name = filter.attr_name
                             AND pav.value = filter.attr_value
                       )
                       )
                   GROUP BY
                       ptav.product_id
                   HAVING
                       COUNT(DISTINCT pa.name) = (SELECT COUNT(*) FROM jsonb_each_text($4::jsonb))
               ),
               final_products AS (
                   SELECT DISTINCT
                       fp.id, fp.name, fp.description, fp.price_in_kes, fp.slug, fp.discount_percent, fp.image_url, fp.created_at
                   FROM
                       filtered_products fp
                           JOIN
                       filtered_attributes fa ON fp.id = fa.product_id
               )
SELECT
    fp.id,
    fp.name,
    fp.description,
    fp.price_in_kes AS price,
    fp.image_url AS imageURL,
    fp.discount_percent AS discountPercent,
    fp.slug,
    fp.created_at
FROM
    final_products fp
ORDER BY
    fp.created_at ASC
LIMIT
    $5 OFFSET $6
`

type GetAllProductsByFiltersOldestParams struct {
	Column1    []string
	UsdPrice   string
	UsdPrice_2 string
	Column4    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetAllProductsByFiltersOldestRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Imageurl        string
	Discountpercent string
	Slug            string
	CreatedAt       sql.NullTime
}

func (q *Queries) GetAllProductsByFiltersOldest(ctx context.Context, arg GetAllProductsByFiltersOldestParams) ([]GetAllProductsByFiltersOldestRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsByFiltersOldest,
		pq.Array(arg.Column1),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsByFiltersOldestRow
	for rows.Next() {
		var i GetAllProductsByFiltersOldestRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Imageurl,
			&i.Discountpercent,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProductsByFiltersPriceAsc = `-- name: GetAllProductsByFiltersPriceAsc :many
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
    WHERE
        c.name = ANY($1::VARCHAR[]) OR $1 IS NULL

    UNION ALL

    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
            JOIN
        category_hierarchy ch ON c.parent_id = ch.id
),
               rate AS (
                   SELECT COALESCE(
                                  (SELECT rate_to_kes
                                   FROM exchange_rates
                                   WHERE currency_code = 'USD'
                                     AND (valid_to IS NULL OR valid_to >= NOW())
                                     AND valid_from <= NOW()
                                   ORDER BY valid_from DESC
                                   LIMIT 1),
                                  135) AS rate_to_kes
               ),
               filtered_products AS (
                   SELECT
                       p.id,
                       p.name,
                       p.description,
                       (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric AS price_in_kes,
                       p.slug,
                       COALESCE(
                               (SELECT MAX(d.discount_percentage)
                                FROM discounts d
                                WHERE d.product_id = p.id
                                  AND d.start_date <= NOW()
                                  AND (d.end_date IS NULL OR d.end_date >= NOW())
                               ), 0)::numeric AS discount_percent,
                       (SELECT pi.image_url
                        FROM product_images pi
                        WHERE pi.product_id = p.id
                        ORDER BY pi.position ASC
                        LIMIT 1) AS image_url
                   FROM
                       products p
                   WHERE
                       (p.category_id IN (SELECT id FROM category_hierarchy) OR $1 IS NULL)
                     AND (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric BETWEEN $2 AND $3
                     AND p.status = 'active'
               ),
               filtered_attributes AS (
                   SELECT
                       ptav.product_id
                   FROM
                       product_to_attribute_values ptav
                           JOIN
                       product_attribute_values pav ON ptav.attribute_value_id = pav.id
                           JOIN
                       product_attributes pa ON pav.attribute_id = pa.id
                   WHERE
                       ptav.product_id IN (SELECT id FROM filtered_products)
                     AND (
                       jsonb_typeof($4::jsonb) IS NULL
                           OR EXISTS (
                           SELECT 1
                           FROM jsonb_each_text($4::jsonb) AS filter(attr_name, attr_value)
                           WHERE pa.name = filter.attr_name
                             AND pav.value = filter.attr_value
                       )
                       )
                   GROUP BY
                       ptav.product_id
                   HAVING
                       COUNT(DISTINCT pa.name) = (SELECT COUNT(*) FROM jsonb_each_text($4::jsonb))
               ),
               final_products AS (
                   SELECT DISTINCT
                       fp.id, fp.name, fp.description, fp.price_in_kes, fp.slug, fp.discount_percent, fp.image_url
                   FROM
                       filtered_products fp
                           JOIN
                       filtered_attributes fa ON fp.id = fa.product_id
               )
SELECT
    fp.id,
    fp.name,
    fp.description,
    fp.price_in_kes AS price,
    fp.image_url AS imageURL,
    fp.discount_percent AS discountPercent,
    fp.slug
FROM
    final_products fp
ORDER BY
    fp.price_in_kes ASC
LIMIT
    $5 OFFSET $6
`

type GetAllProductsByFiltersPriceAscParams struct {
	Column1    []string
	UsdPrice   string
	UsdPrice_2 string
	Column4    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetAllProductsByFiltersPriceAscRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Imageurl        string
	Discountpercent string
	Slug            string
}

func (q *Queries) GetAllProductsByFiltersPriceAsc(ctx context.Context, arg GetAllProductsByFiltersPriceAscParams) ([]GetAllProductsByFiltersPriceAscRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsByFiltersPriceAsc,
		pq.Array(arg.Column1),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsByFiltersPriceAscRow
	for rows.Next() {
		var i GetAllProductsByFiltersPriceAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Imageurl,
			&i.Discountpercent,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProductsByFiltersPriceDesc = `-- name: GetAllProductsByFiltersPriceDesc :many
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
    WHERE
        c.name = ANY($1::VARCHAR[]) OR $1 IS NULL

    UNION ALL

    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
            JOIN
        category_hierarchy ch ON c.parent_id = ch.id
),
               rate AS (
                   SELECT COALESCE(
                                  (SELECT rate_to_kes
                                   FROM exchange_rates
                                   WHERE currency_code = 'USD'
                                     AND (valid_to IS NULL OR valid_to >= NOW())
                                     AND valid_from <= NOW()
                                   ORDER BY valid_from DESC
                                   LIMIT 1),
                                  135) AS rate_to_kes
               ),
               filtered_products AS (
                   SELECT
                       p.id,
                       p.name,
                       p.description,
                       (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric AS price_in_kes,
                       p.slug,
                       COALESCE(
                               (SELECT MAX(d.discount_percentage)
                                FROM discounts d
                                WHERE d.product_id = p.id
                                  AND d.start_date <= NOW()
                                  AND (d.end_date IS NULL OR d.end_date >= NOW())
                               ), 0)::numeric AS discount_percent,
                       (SELECT pi.image_url
                        FROM product_images pi
                        WHERE pi.product_id = p.id
                        ORDER BY pi.position ASC
                        LIMIT 1) AS image_url
                   FROM
                       products p
                   WHERE
                       (p.category_id IN (SELECT id FROM category_hierarchy) OR $1 IS NULL)
                     AND (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric BETWEEN $2 AND $3
                     AND p.status = 'active'
               ),
               filtered_attributes AS (
                   SELECT
                       ptav.product_id
                   FROM
                       product_to_attribute_values ptav
                           JOIN
                       product_attribute_values pav ON ptav.attribute_value_id = pav.id
                           JOIN
                       product_attributes pa ON pav.attribute_id = pa.id
                   WHERE
                       ptav.product_id IN (SELECT id FROM filtered_products)
                     AND (
                       jsonb_typeof($4::jsonb) IS NULL
                           OR EXISTS (
                           SELECT 1
                           FROM jsonb_each_text($4::jsonb) AS filter(attr_name, attr_value)
                           WHERE pa.name = filter.attr_name
                             AND pav.value = filter.attr_value
                       )
                       )
                   GROUP BY
                       ptav.product_id
                   HAVING
                       COUNT(DISTINCT pa.name) = (SELECT COUNT(*) FROM jsonb_each_text($4::jsonb))
               ),
               final_products AS (
                   SELECT DISTINCT
                       fp.id, fp.name, fp.description, fp.price_in_kes, fp.slug, fp.discount_percent, fp.image_url
                   FROM
                       filtered_products fp
                           JOIN
                       filtered_attributes fa ON fp.id = fa.product_id
               )
SELECT
    fp.id,
    fp.name,
    fp.description,
    fp.price_in_kes AS price,
    fp.image_url AS imageURL,
    fp.discount_percent AS discountPercent,
    fp.slug
FROM
    final_products fp
ORDER BY
    fp.price_in_kes DESC
LIMIT
    $5 OFFSET $6
`

type GetAllProductsByFiltersPriceDescParams struct {
	Column1    []string
	UsdPrice   string
	UsdPrice_2 string
	Column4    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetAllProductsByFiltersPriceDescRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Imageurl        string
	Discountpercent string
	Slug            string
}

func (q *Queries) GetAllProductsByFiltersPriceDesc(ctx context.Context, arg GetAllProductsByFiltersPriceDescParams) ([]GetAllProductsByFiltersPriceDescRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsByFiltersPriceDesc,
		pq.Array(arg.Column1),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsByFiltersPriceDescRow
	for rows.Next() {
		var i GetAllProductsByFiltersPriceDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Imageurl,
			&i.Discountpercent,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductAttributes = `-- name: GetProductAttributes :one
WITH all_active_products AS (
    SELECT p.id
    FROM products p
    WHERE p.status = 'active'
),
     attribute_values AS (
         SELECT
             pa.name AS attribute_name,
             pav.value AS attribute_value
         FROM
             product_to_attribute_values ptav
                 JOIN
             product_attribute_values pav ON ptav.attribute_value_id = pav.id
                 JOIN
             product_attributes pa ON pav.attribute_id = pa.id
         WHERE
             ptav.product_id IN (SELECT id FROM all_active_products)
     )
SELECT
    jsonb_agg(
            jsonb_build_object(
                    attribute_name, jsonb_agg(DISTINCT attribute_value)
            )
    ) AS attributes,
    (SELECT COUNT(*) FROM all_active_products) AS total_products
FROM
    attribute_values
GROUP BY
    attribute_name
`

type GetProductAttributesRow struct {
	Attributes    json.RawMessage
	TotalProducts int64
}

func (q *Queries) GetProductAttributes(ctx context.Context) (GetProductAttributesRow, error) {
	row := q.db.QueryRowContext(ctx, getProductAttributes)
	var i GetProductAttributesRow
	err := row.Scan(&i.Attributes, &i.TotalProducts)
	return i, err
}
