// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: filter_category_products.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getCategoryProductsByFiltersNameAsc = `-- name: GetCategoryProductsByFiltersNameAsc :many
WITH RECURSIVE category_tree AS (
    SELECT c.id, c.name
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id, c.name
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
), rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
SELECT DISTINCT
    p.id,
    p.name,
    p.description,
    (p.usd_price * rate.rate_to_kes)::numeric AS price,
    p.slug,
    COALESCE(
            (SELECT MAX(d.discount_percentage)
             FROM discounts d
             WHERE d.product_id = p.id
               AND d.start_date <= NOW()
               AND (d.end_date IS NULL OR d.end_date >= NOW())
            ), 0)::numeric AS discountPercent,
    (SELECT pi.image_url
     FROM product_images pi
     WHERE pi.product_id = p.id
     ORDER BY pi.position ASC
     LIMIT 1) AS imageURL
FROM products p
         JOIN category_tree ct ON p.category_id = ct.id
         LEFT JOIN product_to_attribute_values ptav ON p.id = ptav.product_id
         LEFT JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
         LEFT JOIN product_attributes pa ON pav.attribute_id = pa.id,
     rate
WHERE (array_length($2::text[], 1) IS NULL OR ct.name = ANY($2))
  AND (
      jsonb_typeof($5::jsonb) IS NULL 
      OR jsonb_each_text($5::jsonb) ->> pa.name IS NOT NULL 
      AND pav.value = (jsonb_each_text($5::jsonb) ->> pa.name)
  )
  AND (p.usd_price * rate.rate_to_kes)::numeric BETWEEN $3 AND $4
  AND p.status = 'active'
ORDER BY p.name ASC
LIMIT $6 OFFSET $7
`

type GetCategoryProductsByFiltersNameAscParams struct {
	ID         uuid.UUID
	Column2    []string
	UsdPrice   string
	UsdPrice_2 string
	Column5    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetCategoryProductsByFiltersNameAscRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Slug            string
	Discountpercent string
	Imageurl        string
}

// $1: category_id (UUID)
// $2: selected_category_names (VARCHAR[])
// $3: min_price_kes (NUMERIC)
// $4: max_price_kes (NUMERIC)
// $5: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
// $6: limit (INTEGER)
// $7: offset (INTEGER)
func (q *Queries) GetCategoryProductsByFiltersNameAsc(ctx context.Context, arg GetCategoryProductsByFiltersNameAscParams) ([]GetCategoryProductsByFiltersNameAscRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryProductsByFiltersNameAsc,
		arg.ID,
		pq.Array(arg.Column2),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryProductsByFiltersNameAscRow
	for rows.Next() {
		var i GetCategoryProductsByFiltersNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Slug,
			&i.Discountpercent,
			&i.Imageurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryProductsByFiltersNameDesc = `-- name: GetCategoryProductsByFiltersNameDesc :many
WITH RECURSIVE category_tree AS (
    SELECT c.id, c.name
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id, c.name
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
), rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
SELECT DISTINCT
    p.id,
    p.name,
    p.description,
    (p.usd_price * rate.rate_to_kes)::numeric AS price,
    p.slug,
    COALESCE(
            (SELECT MAX(d.discount_percentage)
             FROM discounts d
             WHERE d.product_id = p.id
               AND d.start_date <= NOW()
               AND (d.end_date IS NULL OR d.end_date >= NOW())
            ), 0)::numeric AS discountPercent,
    (SELECT pi.image_url
     FROM product_images pi
     WHERE pi.product_id = p.id
     ORDER BY pi.position ASC
     LIMIT 1) AS imageURL
FROM products p
         JOIN category_tree ct ON p.category_id = ct.id
         LEFT JOIN product_to_attribute_values ptav ON p.id = ptav.product_id
         LEFT JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
         LEFT JOIN product_attributes pa ON pav.attribute_id = pa.id,
     rate
WHERE (array_length($2::text[], 1) IS NULL OR ct.name = ANY($2))
  AND (
      jsonb_typeof($5::jsonb) IS NULL 
      OR jsonb_each_text($5::jsonb) ->> pa.name IS NOT NULL 
      AND pav.value = (jsonb_each_text($5::jsonb) ->> pa.name)
  )
  AND (p.usd_price * rate.rate_to_kes)::numeric BETWEEN $3 AND $4
  AND p.status = 'active'
ORDER BY p.name DESC
LIMIT $6 OFFSET $7
`

type GetCategoryProductsByFiltersNameDescParams struct {
	ID         uuid.UUID
	Column2    []string
	UsdPrice   string
	UsdPrice_2 string
	Column5    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetCategoryProductsByFiltersNameDescRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Slug            string
	Discountpercent string
	Imageurl        string
}

// $1: category_id (UUID)
// $2: selected_category_names (VARCHAR[])
// $3: min_price_kes (NUMERIC)
// $4: max_price_kes (NUMERIC)
// $5: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
// $6: limit (INTEGER)
// $7: offset (INTEGER)
func (q *Queries) GetCategoryProductsByFiltersNameDesc(ctx context.Context, arg GetCategoryProductsByFiltersNameDescParams) ([]GetCategoryProductsByFiltersNameDescRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryProductsByFiltersNameDesc,
		arg.ID,
		pq.Array(arg.Column2),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryProductsByFiltersNameDescRow
	for rows.Next() {
		var i GetCategoryProductsByFiltersNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Slug,
			&i.Discountpercent,
			&i.Imageurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryProductsByFiltersNewest = `-- name: GetCategoryProductsByFiltersNewest :many
WITH RECURSIVE category_tree AS (
    SELECT c.id, c.name
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id, c.name
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
), rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
SELECT DISTINCT
    p.id,
    p.name,
    p.description,
    (p.usd_price * rate.rate_to_kes)::numeric AS price,
    p.slug,
    COALESCE(
            (SELECT MAX(d.discount_percentage)
             FROM discounts d
             WHERE d.product_id = p.id
               AND d.start_date <= NOW()
               AND (d.end_date IS NULL OR d.end_date >= NOW())
            ), 0)::numeric AS discountPercent,
    (SELECT pi.image_url
     FROM product_images pi
     WHERE pi.product_id = p.id
     ORDER BY pi.position ASC
     LIMIT 1) AS imageURL
FROM products p
         JOIN category_tree ct ON p.category_id = ct.id
         LEFT JOIN product_to_attribute_values ptav ON p.id = ptav.product_id
         LEFT JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
         LEFT JOIN product_attributes pa ON pav.attribute_id = pa.id,
     rate
WHERE (array_length($2::text[], 1) IS NULL OR ct.name = ANY($2))
  AND (
      jsonb_typeof($5::jsonb) IS NULL 
      OR jsonb_each_text($5::jsonb) ->> pa.name IS NOT NULL 
      AND pav.value = (jsonb_each_text($5::jsonb) ->> pa.name)
  )
  AND (p.usd_price * rate.rate_to_kes)::numeric BETWEEN $3 AND $4
  AND p.status = 'active'
ORDER BY p.created_at DESC
LIMIT $6 OFFSET $7
`

type GetCategoryProductsByFiltersNewestParams struct {
	ID         uuid.UUID
	Column2    []string
	UsdPrice   string
	UsdPrice_2 string
	Column5    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetCategoryProductsByFiltersNewestRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Slug            string
	Discountpercent string
	Imageurl        string
}

// $1: category_id (UUID)
// $2: selected_category_names (VARCHAR[])
// $3: min_price_kes (NUMERIC)
// $4: max_price_kes (NUMERIC)
// $5: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
// $6: limit (INTEGER)
// $7: offset (INTEGER)
func (q *Queries) GetCategoryProductsByFiltersNewest(ctx context.Context, arg GetCategoryProductsByFiltersNewestParams) ([]GetCategoryProductsByFiltersNewestRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryProductsByFiltersNewest,
		arg.ID,
		pq.Array(arg.Column2),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryProductsByFiltersNewestRow
	for rows.Next() {
		var i GetCategoryProductsByFiltersNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Slug,
			&i.Discountpercent,
			&i.Imageurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryProductsByFiltersOldest = `-- name: GetCategoryProductsByFiltersOldest :many
WITH RECURSIVE category_tree AS (
    SELECT c.id, c.name
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id, c.name
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
), rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
SELECT DISTINCT
    p.id,
    p.name,
    p.description,
    (p.usd_price * rate.rate_to_kes)::numeric AS price,
    p.slug,
    COALESCE(
            (SELECT MAX(d.discount_percentage)
             FROM discounts d
             WHERE d.product_id = p.id
               AND d.start_date <= NOW()
               AND (d.end_date IS NULL OR d.end_date >= NOW())
            ), 0)::numeric AS discountPercent,
    (SELECT pi.image_url
     FROM product_images pi
     WHERE pi.product_id = p.id
     ORDER BY pi.position ASC
     LIMIT 1) AS imageURL
FROM products p
         JOIN category_tree ct ON p.category_id = ct.id
         LEFT JOIN product_to_attribute_values ptav ON p.id = ptav.product_id
         LEFT JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
         LEFT JOIN product_attributes pa ON pav.attribute_id = pa.id,
     rate
WHERE (array_length($2::text[], 1) IS NULL OR ct.name = ANY($2))
  AND (
      jsonb_typeof($5::jsonb) IS NULL 
      OR jsonb_each_text($5::jsonb) ->> pa.name IS NOT NULL 
      AND pav.value = (jsonb_each_text($5::jsonb) ->> pa.name)
  )
  AND (p.usd_price * rate.rate_to_kes)::numeric BETWEEN $3 AND $4
  AND p.status = 'active'
ORDER BY p.created_at ASC
LIMIT $6 OFFSET $7
`

type GetCategoryProductsByFiltersOldestParams struct {
	ID         uuid.UUID
	Column2    []string
	UsdPrice   string
	UsdPrice_2 string
	Column5    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetCategoryProductsByFiltersOldestRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Slug            string
	Discountpercent string
	Imageurl        string
}

// $1: category_id (UUID)
// $2: selected_category_names (VARCHAR[])
// $3: min_price_kes (NUMERIC)
// $4: max_price_kes (NUMERIC)
// $5: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
// $6: limit (INTEGER)
// $7: offset (INTEGER)
func (q *Queries) GetCategoryProductsByFiltersOldest(ctx context.Context, arg GetCategoryProductsByFiltersOldestParams) ([]GetCategoryProductsByFiltersOldestRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryProductsByFiltersOldest,
		arg.ID,
		pq.Array(arg.Column2),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryProductsByFiltersOldestRow
	for rows.Next() {
		var i GetCategoryProductsByFiltersOldestRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Slug,
			&i.Discountpercent,
			&i.Imageurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryProductsByFiltersPriceAsc = `-- name: GetCategoryProductsByFiltersPriceAsc :many
WITH RECURSIVE category_tree AS (
    SELECT c.id, c.name
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id, c.name
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
), rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
SELECT DISTINCT
    p.id,
    p.name,
    p.description,
    (p.usd_price * rate.rate_to_kes)::numeric AS price,
    p.slug,
    COALESCE(
            (SELECT MAX(d.discount_percentage)
             FROM discounts d
             WHERE d.product_id = p.id
               AND d.start_date <= NOW()
               AND (d.end_date IS NULL OR d.end_date >= NOW())
            ), 0)::numeric AS discountPercent,
    (SELECT pi.image_url
     FROM product_images pi
     WHERE pi.product_id = p.id
     ORDER BY pi.position ASC
     LIMIT 1) AS imageURL
FROM products p
         JOIN category_tree ct ON p.category_id = ct.id
         LEFT JOIN product_to_attribute_values ptav ON p.id = ptav.product_id
         LEFT JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
         LEFT JOIN product_attributes pa ON pav.attribute_id = pa.id,
     rate
WHERE (array_length($2::text[], 1) IS NULL OR ct.name = ANY($2))
  AND (
      jsonb_typeof($5::jsonb) IS NULL 
      OR jsonb_each_text($5::jsonb) ->> pa.name IS NOT NULL 
      AND pav.value = (jsonb_each_text($5::jsonb) ->> pa.name)
  )
  AND (p.usd_price * rate.rate_to_kes)::numeric BETWEEN $3 AND $4
  AND p.status = 'active'
ORDER BY p.usd_price ASC
LIMIT $6 OFFSET $7
`

type GetCategoryProductsByFiltersPriceAscParams struct {
	ID         uuid.UUID
	Column2    []string
	UsdPrice   string
	UsdPrice_2 string
	Column5    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetCategoryProductsByFiltersPriceAscRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Slug            string
	Discountpercent string
	Imageurl        string
}

// $1: category_id (UUID)
// $2: selected_category_names (VARCHAR[])
// $3: min_price_kes (NUMERIC)
// $4: max_price_kes (NUMERIC)
// $5: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
// $6: limit (INTEGER)
// $7: offset (INTEGER)
func (q *Queries) GetCategoryProductsByFiltersPriceAsc(ctx context.Context, arg GetCategoryProductsByFiltersPriceAscParams) ([]GetCategoryProductsByFiltersPriceAscRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryProductsByFiltersPriceAsc,
		arg.ID,
		pq.Array(arg.Column2),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryProductsByFiltersPriceAscRow
	for rows.Next() {
		var i GetCategoryProductsByFiltersPriceAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Slug,
			&i.Discountpercent,
			&i.Imageurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryProductsByFiltersPriceDesc = `-- name: GetCategoryProductsByFiltersPriceDesc :many
WITH RECURSIVE category_tree AS (
    SELECT c.id, c.name
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id, c.name
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
), rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
SELECT DISTINCT
    p.id,
    p.name,
    p.description,
    (p.usd_price * rate.rate_to_kes)::numeric AS price,
    p.slug,
    COALESCE(
            (SELECT MAX(d.discount_percentage)
             FROM discounts d
             WHERE d.product_id = p.id
               AND d.start_date <= NOW()
               AND (d.end_date IS NULL OR d.end_date >= NOW())
            ), 0)::numeric AS discountPercent,
    (SELECT pi.image_url
     FROM product_images pi
     WHERE pi.product_id = p.id
     ORDER BY pi.position ASC
     LIMIT 1) AS imageURL
FROM products p
         JOIN category_tree ct ON p.category_id = ct.id
         LEFT JOIN product_to_attribute_values ptav ON p.id = ptav.product_id
         LEFT JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
         LEFT JOIN product_attributes pa ON pav.attribute_id = pa.id,
     rate
WHERE (array_length($2::text[], 1) IS NULL OR ct.name = ANY($2))
  AND (
      jsonb_typeof($5::jsonb) IS NULL 
      OR jsonb_each_text($5::jsonb) ->> pa.name IS NOT NULL 
      AND pav.value = (jsonb_each_text($5::jsonb) ->> pa.name)
  )
  AND (p.usd_price * rate.rate_to_kes)::numeric BETWEEN $3 AND $4
  AND p.status = 'active'
ORDER BY p.usd_price DESC
LIMIT $6 OFFSET $7
`

type GetCategoryProductsByFiltersPriceDescParams struct {
	ID         uuid.UUID
	Column2    []string
	UsdPrice   string
	UsdPrice_2 string
	Column5    json.RawMessage
	Limit      int32
	Offset     int32
}

type GetCategoryProductsByFiltersPriceDescRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           string
	Slug            string
	Discountpercent string
	Imageurl        string
}

// $1: category_id (UUID)
// $2: selected_category_names (VARCHAR[])
// $3: min_price_kes (NUMERIC)
// $4: max_price_kes (NUMERIC)
// $5: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
// $6: limit (INTEGER)
// $7: offset (INTEGER)
func (q *Queries) GetCategoryProductsByFiltersPriceDesc(ctx context.Context, arg GetCategoryProductsByFiltersPriceDescParams) ([]GetCategoryProductsByFiltersPriceDescRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryProductsByFiltersPriceDesc,
		arg.ID,
		pq.Array(arg.Column2),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryProductsByFiltersPriceDescRow
	for rows.Next() {
		var i GetCategoryProductsByFiltersPriceDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Slug,
			&i.Discountpercent,
			&i.Imageurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductAttributesByCategoryID = `-- name: GetProductAttributesByCategoryID :one
WITH category_products AS (
    SELECT p.id
    FROM products p
    WHERE p.category_id = $1 AND p.status = 'active'
),
     attribute_values AS (
         SELECT
             pa.name AS attribute_name,
             pav.value AS attribute_value
         FROM
             product_to_attribute_values ptav
                 JOIN
             product_attribute_values pav ON ptav.attribute_value_id = pav.id
                 JOIN
             product_attributes pa ON pav.attribute_id = pa.id
         WHERE
             ptav.product_id IN (SELECT id FROM category_products)
     )
SELECT
    jsonb_agg(
            jsonb_build_object(
                    attribute_name, jsonb_agg(DISTINCT attribute_value)
            )
    ) AS attributes,
    (SELECT COUNT(*) FROM category_products) AS total_products
FROM
    attribute_values
GROUP BY
    attribute_name
`

type GetProductAttributesByCategoryIDRow struct {
	Attributes    json.RawMessage
	TotalProducts int64
}

func (q *Queries) GetProductAttributesByCategoryID(ctx context.Context, categoryID uuid.UUID) (GetProductAttributesByCategoryIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductAttributesByCategoryID, categoryID)
	var i GetProductAttributesByCategoryIDRow
	err := row.Scan(&i.Attributes, &i.TotalProducts)
	return i, err
}

const getTotalCategoryProductsByFilters = `-- name: GetTotalCategoryProductsByFilters :one


WITH RECURSIVE category_tree AS (
    SELECT c.id, c.name
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id, c.name
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
), rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
SELECT COUNT(DISTINCT p.id) AS total_count
FROM products p
         JOIN category_tree ct ON p.category_id = ct.id
         LEFT JOIN product_to_attribute_values ptav ON p.id = ptav.product_id
         LEFT JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
         LEFT JOIN product_attributes pa ON pav.attribute_id = pa.id,
     rate
WHERE (array_length($2::text[], 1) IS NULL OR ct.name = ANY($2))
  AND (
    jsonb_typeof($5::jsonb) IS NULL
        OR jsonb_each_text($5::jsonb) ->> pa.name IS NOT NULL
        AND pav.value = (jsonb_each_text($5::jsonb) ->> pa.name)
    )
  AND (p.usd_price * rate.rate_to_kes)::numeric BETWEEN $3 AND $4
  AND p.status = 'active'
`

type GetTotalCategoryProductsByFiltersParams struct {
	ID         uuid.UUID
	Column2    []string
	UsdPrice   string
	UsdPrice_2 string
	Column5    json.RawMessage
}

// -- name: CountFilteredCategoryProducts :one
// -- $1: selected_category_names (VARCHAR[]) sqlc.arg(selectedCategoryNames)
// -- $2: min_price_kes (NUMERIC) sqlc.arg(minPriceKES)
// -- $3: max_price_kes (NUMERIC) sqlc.arg(maxPriceKES)
// -- $4: selected_attribute_names (VARCHAR[]) sqlc.arg(selectedAttributeNames)
// -- $5: selected_attribute_values (VARCHAR[]) sqlc.arg(selectedAttributeValues)
// WITH RECURSIVE category_hierarchy AS (
//
//	SELECT
//	    c.id,
//	    c.name,
//	    c.parent_id
//	FROM
//	    categories c
//	WHERE
//	    c.name = ANY($1::VARCHAR[]) -- Start with the given list of category names
//
//	UNION ALL
//
//	SELECT
//	    c.id,
//	    c.name,
//	    c.parent_id
//	FROM
//	    categories c
//	        INNER JOIN
//	    category_hierarchy ch ON c.parent_id = ch.id
//
// ),
//
//	current_exchange_rate AS (
//	    SELECT
//	        COALESCE((
//	                     SELECT rate_to_kes
//	                     FROM exchange_rates
//	                     WHERE currency_code = 'USD'
//	                       AND (valid_to IS NULL OR valid_to >= NOW())
//	                     ORDER BY valid_from DESC
//	                     LIMIT 1
//	                 ), 135) AS rate_to_kes
//	),
//	filtered_products AS (
//	    SELECT
//	        p.id
//	    FROM
//	        products p
//	            LEFT JOIN product_to_attribute_values ptav ON p.id = ptav.product_id
//	            LEFT JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
//	            LEFT JOIN product_attributes pa ON pav.attribute_id = pa.id,
//	        current_exchange_rate er
//	    WHERE
//	        p.category_id IN (SELECT id FROM category_hierarchy)
//	      -- Attribute filters
//	      AND (
//	        (
//	            pa.name = ANY($4::VARCHAR[]) AND
//	            pav.value = ANY($5::VARCHAR[])
//	            )
//	            OR $4 IS NULL
//	        )
//	      -- Price range filter (converted to KES)
//	      AND (p.usd_price * er.rate_to_kes) BETWEEN $2::numeric AND $3::numeric
//	      -- Status filter
//	      AND p.status = 'active'
//	)
//
// SELECT COUNT(*) AS total_count FROM filtered_products;
// $1: category_id (UUID)
// $2: selected_category_names (VARCHAR[])
// $3: min_price_kes (NUMERIC)
// $4: max_price_kes (NUMERIC)
// $5: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
func (q *Queries) GetTotalCategoryProductsByFilters(ctx context.Context, arg GetTotalCategoryProductsByFiltersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCategoryProductsByFilters,
		arg.ID,
		pq.Array(arg.Column2),
		arg.UsdPrice,
		arg.UsdPrice_2,
		arg.Column5,
	)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}
