// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type CartItem struct {
	ID             uuid.UUID
	ShoppingCartID uuid.NullUUID
	ProductID      uuid.NullUUID
	Quantity       int32
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Price          string
}

type Category struct {
	ID        uuid.UUID
	Name      string
	ParentID  uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	IsActive  bool
	Position  int32
	ImageUrl  sql.NullString
}

type Color struct {
	ID         uuid.UUID
	ColorName  string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	ColorValue sql.NullString
}

type Color struct {
	ID         uuid.UUID
	ColorName  string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	ColorValue sql.NullString
}

type Discount struct {
	ID                 uuid.UUID
	ProductID          uuid.NullUUID
	DiscountPercentage string
	StartDate          sql.NullTime
	EndDate            sql.NullTime
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type GuestCheckout struct {
	ID            uuid.UUID
	Email         string
	FirstName     string
	LastName      string
	Phone         sql.NullString
	StreetAddress string
	City          string
	State         string
	Country       string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Order struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	Status          string
	Total           string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	PaymentStatus   string
	GuestCheckoutID uuid.NullUUID
	OrderNumber     sql.NullString
}

type OrderItem struct {
	ID        uuid.UUID
	OrderID   uuid.NullUUID
	ProductID uuid.NullUUID
	Quantity  int32
	Price     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type OrderItemOption struct {
	ID              uuid.UUID
	OrderItemID     uuid.NullUUID
	OptionType      string
	OptionValue     string
	AdditionalPrice sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type OrderPayment struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	Amount            string
	CreatedAt         sql.NullTime
	PaymentMethodID   sql.NullInt32
	PaymentStatusID   sql.NullInt32
	CheckoutRequestID string
	ResultCode        sql.NullInt32
	ResultDesc        sql.NullString
	UpdatedAt         sql.NullTime
}

type OrderShipment struct {
	ID         uuid.UUID
	OrderID    uuid.NullUUID
	TrackingID string
	Status     string
	CreatedAt  sql.NullTime
}

type OrderStatusHistory struct {
	ID        uuid.UUID
	OrderID   uuid.NullUUID
	Status    string
	CreatedAt sql.NullTime
}

type PaymentMethod struct {
	ID     int32
	Method string
}

type PaymentStatus struct {
	ID     int32
	Status string
}

type Processor struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Product struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	Price         string
	Stock         sql.NullInt32
	CategoryID    uuid.NullUUID
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	IsActive      sql.NullBool
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
	Featured      sql.NullBool
	SearchKeyword interface{}
}

type ProductColor struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ColorID   uuid.NullUUID
}

type ProductImage struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	ImageUrl  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ProductInteraction struct {
	ID              uuid.UUID
	ProductID       uuid.NullUUID
	InteractionType string
	UserID          uuid.NullUUID
	InteractionTime sql.NullTime
}

type ProductOption struct {
	ID         uuid.UUID
	ProductID  uuid.NullUUID
	OptionName string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type ProductOptionValue struct {
	ID              uuid.UUID
	OptionID        uuid.NullUUID
	ValueName       string
	AdditionalPrice sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ProductProcessor struct {
	ID          uuid.UUID
	ProductID   uuid.NullUUID
	ProcessorID uuid.NullUUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type ProductReview struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	UserID    uuid.NullUUID
	Rating    sql.NullInt32
	Comment   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ProductSize struct {
	ID              uuid.UUID
	ProductID       uuid.NullUUID
	AdditionalPrice sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	SizeID          uuid.NullUUID
}

type ProductSpecification struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	SpecName  string
	SpecValue string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ProductStorageOption struct {
	ID              uuid.UUID
	ProductID       uuid.NullUUID
	StorageOptionID uuid.NullUUID
	AdditionalPrice sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ProductVariant struct {
	ID           uuid.UUID
	ProductID    uuid.NullUUID
	VariantName  string
	VariantValue string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Price        string
	Stock        sql.NullInt32
}

type Recommendation struct {
	UserID    uuid.NullUUID
	ProductID uuid.NullUUID
	Score     int64
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type RelatedProduct struct {
	ProductID        uuid.UUID
	RelatedProductID uuid.UUID
}

type Shipment struct {
	ID             uuid.UUID
	OrderID        uuid.NullUUID
	ShipmentStatus string
	TrackingNumber sql.NullString
	ShippedDate    sql.NullTime
	DeliveryDate   sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type ShoppingCart struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	SessionID  uuid.NullUUID
	TotalItems int32
	TotalPrice string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Size struct {
	ID        uuid.UUID
	Size      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type StorageOption struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID              uuid.UUID
	Email           string
	HashedPassword  string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

type UserAddress struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Address   json.RawMessage
	IsDefault sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserPreference struct {
	UserID           uuid.NullUUID
	ProductID        uuid.NullUUID
	InteractionCount int64
}

type UserRole struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Role      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Wishlist struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type WishlistItem struct {
	ID         uuid.UUID
	WishlistID uuid.NullUUID
	ProductID  uuid.NullUUID
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
