// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, guest_email, status, payment_status, total, created_at, updated_at)
VALUES ($1, $2, $3, 'pending', 'pending', $4, NOW(), NOW())
    RETURNING id
`

type CreateOrderParams struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	GuestEmail sql.NullString
	Total      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.GuestEmail,
		arg.Total,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, user_id, guest_email, status, payment_status, total, created_at, updated_at
FROM orders
WHERE id = $1
`

type GetOrderByIdRow struct {
	ID            uuid.UUID
	UserID        uuid.NullUUID
	GuestEmail    sql.NullString
	Status        string
	PaymentStatus string
	Total         string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

func (q *Queries) GetOrderById(ctx context.Context, id uuid.UUID) (GetOrderByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderById, id)
	var i GetOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestEmail,
		&i.Status,
		&i.PaymentStatus,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByGuestEmail = `-- name: GetOrdersByGuestEmail :many
SELECT id, user_id, guest_email, status, payment_status, total, created_at, updated_at
FROM orders
WHERE guest_email = $1
ORDER BY created_at DESC
`

type GetOrdersByGuestEmailRow struct {
	ID            uuid.UUID
	UserID        uuid.NullUUID
	GuestEmail    sql.NullString
	Status        string
	PaymentStatus string
	Total         string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

func (q *Queries) GetOrdersByGuestEmail(ctx context.Context, guestEmail sql.NullString) ([]GetOrdersByGuestEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByGuestEmail, guestEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByGuestEmailRow
	for rows.Next() {
		var i GetOrdersByGuestEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestEmail,
			&i.Status,
			&i.PaymentStatus,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserId = `-- name: GetOrdersByUserId :many
SELECT id, user_id, guest_email, status, payment_status, total, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetOrdersByUserIdRow struct {
	ID            uuid.UUID
	UserID        uuid.NullUUID
	GuestEmail    sql.NullString
	Status        string
	PaymentStatus string
	Total         string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

func (q *Queries) GetOrdersByUserId(ctx context.Context, userID uuid.NullUUID) ([]GetOrdersByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserIdRow
	for rows.Next() {
		var i GetOrdersByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestEmail,
			&i.Status,
			&i.PaymentStatus,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :exec
UPDATE orders
SET payment_status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderPaymentStatusParams struct {
	ID            uuid.UUID
	PaymentStatus string
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderPaymentStatus, arg.ID, arg.PaymentStatus)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
