// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGuestCheckout = `-- name: CreateGuestCheckout :one
INSERT INTO guest_checkouts (id, email, first_name, last_name, phone, street_address, city, state, country, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id
`

type CreateGuestCheckoutParams struct {
	Email         string
	FirstName     string
	LastName      string
	Phone         sql.NullString
	StreetAddress string
	City          string
	State         string
	Country       string
}

func (q *Queries) CreateGuestCheckout(ctx context.Context, arg CreateGuestCheckoutParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createGuestCheckout,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.StreetAddress,
		arg.City,
		arg.State,
		arg.Country,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, guest_checkout_id, status, payment_status, total)
VALUES ($1, $2, 'pending', 'pending', $3)
RETURNING id
`

type CreateOrderParams struct {
	UserID          uuid.NullUUID
	GuestCheckoutID uuid.NullUUID
	Total           string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.UserID, arg.GuestCheckoutID, arg.Total)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getGuestCheckoutByEmail = `-- name: GetGuestCheckoutByEmail :one
SELECT id, email, first_name, last_name, phone, street_address, city, state, country, created_at, updated_at
FROM guest_checkouts
WHERE email = $1
`

func (q *Queries) GetGuestCheckoutByEmail(ctx context.Context, email string) (GuestCheckout, error) {
	row := q.db.QueryRowContext(ctx, getGuestCheckoutByEmail, email)
	var i GuestCheckout
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, user_id,guest_checkout_id,  status, payment_status, total, created_at, updated_at, order_number
FROM orders
WHERE id = $1
`

type GetOrderByIdRow struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	GuestCheckoutID uuid.NullUUID
	Status          string
	PaymentStatus   string
	Total           string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	OrderNumber     sql.NullString
}

func (q *Queries) GetOrderById(ctx context.Context, id uuid.UUID) (GetOrderByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderById, id)
	var i GetOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestCheckoutID,
		&i.Status,
		&i.PaymentStatus,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
	)
	return i, err
}

const getOrderIDsByUserID = `-- name: GetOrderIDsByUserID :many
SELECT id
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrderIDsByUserID(ctx context.Context, userID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getOrderIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByGuestCheckoutId = `-- name: GetOrdersByGuestCheckoutId :many
SELECT id, user_id,guest_checkout_id,  status, payment_status, total, created_at, updated_at, order_number
FROM orders
WHERE guest_checkout_id = $1
ORDER BY created_at DESC
`

type GetOrdersByGuestCheckoutIdRow struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	GuestCheckoutID uuid.NullUUID
	Status          string
	PaymentStatus   string
	Total           string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	OrderNumber     sql.NullString
}

func (q *Queries) GetOrdersByGuestCheckoutId(ctx context.Context, guestCheckoutID uuid.NullUUID) ([]GetOrdersByGuestCheckoutIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByGuestCheckoutId, guestCheckoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByGuestCheckoutIdRow
	for rows.Next() {
		var i GetOrdersByGuestCheckoutIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestCheckoutID,
			&i.Status,
			&i.PaymentStatus,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserId = `-- name: GetOrdersByUserId :many
SELECT id, user_id,guest_checkout_id,  status, payment_status, total, created_at, updated_at, order_number
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetOrdersByUserIdRow struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	GuestCheckoutID uuid.NullUUID
	Status          string
	PaymentStatus   string
	Total           string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	OrderNumber     sql.NullString
}

func (q *Queries) GetOrdersByUserId(ctx context.Context, userID uuid.NullUUID) ([]GetOrdersByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserIdRow
	for rows.Next() {
		var i GetOrdersByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestCheckoutID,
			&i.Status,
			&i.PaymentStatus,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOrGuestCheckoutNameByOrderID = `-- name: GetUserOrGuestCheckoutNameByOrderID :one
SELECT
    u.first_name AS user_first_name,
    u.last_name AS user_last_name,
    u.phone_number AS user_phone_number,
    g.first_name AS guest_first_name,
    g.last_name AS guest_last_name,
    g.phone AS guest_phone
FROM orders o
LEFT JOIN users u ON o.user_id = u.id
LEFT JOIN guest_checkouts g ON o.guest_checkout_id = g.id
WHERE o.id = $1
  AND (o.user_id IS NOT NULL OR o.guest_checkout_id IS NOT NULL)
`

type GetUserOrGuestCheckoutNameByOrderIDRow struct {
	UserFirstName   sql.NullString
	UserLastName    sql.NullString
	UserPhoneNumber sql.NullString
	GuestFirstName  sql.NullString
	GuestLastName   sql.NullString
	GuestPhone      sql.NullString
}

func (q *Queries) GetUserOrGuestCheckoutNameByOrderID(ctx context.Context, id uuid.UUID) (GetUserOrGuestCheckoutNameByOrderIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserOrGuestCheckoutNameByOrderID, id)
	var i GetUserOrGuestCheckoutNameByOrderIDRow
	err := row.Scan(
		&i.UserFirstName,
		&i.UserLastName,
		&i.UserPhoneNumber,
		&i.GuestFirstName,
		&i.GuestLastName,
		&i.GuestPhone,
	)
	return i, err
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :exec
UPDATE orders
SET payment_status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderPaymentStatusParams struct {
	ID            uuid.UUID
	PaymentStatus string
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderPaymentStatus, arg.ID, arg.PaymentStatus)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
