// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
RETURNING order_number
`

func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.queryRow(ctx, q.cancelOrderStmt, cancelOrder, id)
	var order_number sql.NullString
	err := row.Scan(&order_number)
	return order_number, err
}

const createGuestCheckout = `-- name: CreateGuestCheckout :one
INSERT INTO guest_checkouts (
    id,
    email,
    first_name,
    last_name,
    phone,
    street_address,
    city,
    state,
    country,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    $1,  -- email
    $2,  -- first_name
    $3,  -- last_name
    $4,  -- phone
    $5,  -- street_address
    $6,  -- city
    $7,  -- state
    $8,  -- country
    now(),
    now()
) RETURNING id
`

type CreateGuestCheckoutParams struct {
	Email         string
	FirstName     string
	LastName      string
	Phone         sql.NullString
	StreetAddress string
	City          string
	State         string
	Country       string
}

func (q *Queries) CreateGuestCheckout(ctx context.Context, arg CreateGuestCheckoutParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.createGuestCheckoutStmt, createGuestCheckout,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.StreetAddress,
		arg.City,
		arg.State,
		arg.Country,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    user_id,
    guest_checkout_id,
    company_id,
    company_name,
    kra_pin,
    currency_code,
    subtotal,
    tax_amount,
    shipping_amount,
    discount_amount,
    grand_total,
    order_number,
    total
) VALUES (
    gen_random_uuid(),
    $1,  -- user_id
    $2,  -- guest_checkout_id
    $3,  -- company_id
    $4,  -- company_name
    $5,  -- kra_pin
    COALESCE($6::text, 'USD'), -- currency_code with default 'USD'
    $7,  -- subtotal
    $8,  -- tax_amount
    $9,  -- shipping_amount
    $10, -- discount_amount
    $11, -- grand_total
    $12,  -- order_number
    $13  -- total
) RETURNING id, order_number, created_at
`

type CreateOrderParams struct {
	UserID          uuid.NullUUID
	GuestCheckoutID uuid.NullUUID
	CompanyID       uuid.NullUUID
	CompanyName     sql.NullString
	KraPin          sql.NullString
	Column6         string
	Subtotal        string
	TaxAmount       string
	ShippingAmount  string
	DiscountAmount  string
	GrandTotal      string
	OrderNumber     sql.NullString
	Total           string
}

type CreateOrderRow struct {
	ID          uuid.UUID
	OrderNumber sql.NullString
	CreatedAt   sql.NullTime
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.queryRow(ctx, q.createOrderStmt, createOrder,
		arg.UserID,
		arg.GuestCheckoutID,
		arg.CompanyID,
		arg.CompanyName,
		arg.KraPin,
		arg.Column6,
		arg.Subtotal,
		arg.TaxAmount,
		arg.ShippingAmount,
		arg.DiscountAmount,
		arg.GrandTotal,
		arg.OrderNumber,
		arg.Total,
	)
	var i CreateOrderRow
	err := row.Scan(&i.ID, &i.OrderNumber, &i.CreatedAt)
	return i, err
}

const getGuestCheckoutByEmail = `-- name: GetGuestCheckoutByEmail :one
SELECT id, email, first_name, last_name, phone, street_address, city, state, country, created_at, updated_at
FROM guest_checkouts
WHERE email = $1
`

func (q *Queries) GetGuestCheckoutByEmail(ctx context.Context, email string) (GuestCheckout, error) {
	row := q.queryRow(ctx, q.getGuestCheckoutByEmailStmt, getGuestCheckoutByEmail, email)
	var i GuestCheckout
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonthlyRevenue = `-- name: GetMonthlyRevenue :many
SELECT
    date_trunc('month', created_at) AS month,
    COALESCE(SUM(amount), 0)::numeric AS total_sales
FROM order_payments
WHERE payment_status_id = $1
GROUP BY month
ORDER BY month DESC
LIMIT 12
`

type GetMonthlyRevenueRow struct {
	Month      int64
	TotalSales string
}

func (q *Queries) GetMonthlyRevenue(ctx context.Context, paymentStatusID sql.NullInt32) ([]GetMonthlyRevenueRow, error) {
	rows, err := q.query(ctx, q.getMonthlyRevenueStmt, getMonthlyRevenue, paymentStatusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyRevenueRow{}
	for rows.Next() {
		var i GetMonthlyRevenueRow
		if err := rows.Scan(&i.Month, &i.TotalSales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySales = `-- name: GetMonthlySales :many
SELECT
    date_trunc('month', created_at) AS month,
    COALESCE(SUM(amount), 0)::numeric AS total_sales
FROM
    order_payments
WHERE
    payment_status_id = $1
GROUP BY
    month
ORDER BY
    month
`

type GetMonthlySalesRow struct {
	Month      int64
	TotalSales string
}

// GetMonthlySales retrieves the total sales for each month from the order_payments table
func (q *Queries) GetMonthlySales(ctx context.Context, paymentStatusID sql.NullInt32) ([]GetMonthlySalesRow, error) {
	rows, err := q.query(ctx, q.getMonthlySalesStmt, getMonthlySales, paymentStatusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySalesRow{}
	for rows.Next() {
		var i GetMonthlySalesRow
		if err := rows.Scan(&i.Month, &i.TotalSales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySalesForLastTwoMonths = `-- name: GetMonthlySalesForLastTwoMonths :one
WITH sales_data AS (
    SELECT
        date_trunc('month', created_at) AS month,
        COALESCE(SUM(amount), 0)::numeric AS total_sales
    FROM order_payments
    WHERE payment_status_id = $1
    GROUP BY month
    ORDER BY month DESC
    LIMIT 2
)
SELECT
    COALESCE(MAX(total_sales), 0)::numeric AS current_month_sales,
    COALESCE(
        (SELECT total_sales FROM sales_data ORDER BY month DESC OFFSET 1 LIMIT 1),
        0
    )::numeric AS previous_month_sales
FROM sales_data
`

type GetMonthlySalesForLastTwoMonthsRow struct {
	CurrentMonthSales  string
	PreviousMonthSales string
}

func (q *Queries) GetMonthlySalesForLastTwoMonths(ctx context.Context, paymentStatusID sql.NullInt32) (GetMonthlySalesForLastTwoMonthsRow, error) {
	row := q.queryRow(ctx, q.getMonthlySalesForLastTwoMonthsStmt, getMonthlySalesForLastTwoMonths, paymentStatusID)
	var i GetMonthlySalesForLastTwoMonthsRow
	err := row.Scan(&i.CurrentMonthSales, &i.PreviousMonthSales)
	return i, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT
    id,
    user_id,
    guest_checkout_id,
    company_id,
    company_name,
    kra_pin,
    status,
    payment_status,
    currency_code,
    subtotal,
    tax_amount,
    shipping_amount,
    discount_amount,
    grand_total,
    created_at,
    updated_at,
    order_number
FROM orders
WHERE id = $1
`

type GetOrderByIdRow struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	GuestCheckoutID uuid.NullUUID
	CompanyID       uuid.NullUUID
	CompanyName     sql.NullString
	KraPin          sql.NullString
	Status          string
	PaymentStatus   string
	CurrencyCode    string
	Subtotal        string
	TaxAmount       string
	ShippingAmount  string
	DiscountAmount  string
	GrandTotal      string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	OrderNumber     sql.NullString
}

func (q *Queries) GetOrderById(ctx context.Context, id uuid.UUID) (GetOrderByIdRow, error) {
	row := q.queryRow(ctx, q.getOrderByIdStmt, getOrderById, id)
	var i GetOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestCheckoutID,
		&i.CompanyID,
		&i.CompanyName,
		&i.KraPin,
		&i.Status,
		&i.PaymentStatus,
		&i.CurrencyCode,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.GrandTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
	)
	return i, err
}

const getOrderIDsByUserID = `-- name: GetOrderIDsByUserID :many
SELECT id
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrderIDsByUserID(ctx context.Context, userID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.query(ctx, q.getOrderIDsByUserIDStmt, getOrderIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByGuestCheckoutId = `-- name: GetOrdersByGuestCheckoutId :many
SELECT
    id,
    user_id,
    guest_checkout_id,
    company_id,
    company_name,
    kra_pin,
    status,
    payment_status,
    currency_code,
    subtotal,
    tax_amount,
    shipping_amount,
    discount_amount,
    grand_total,
    created_at,
    updated_at,
    order_number
FROM orders
WHERE guest_checkout_id = $1
ORDER BY created_at DESC
`

type GetOrdersByGuestCheckoutIdRow struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	GuestCheckoutID uuid.NullUUID
	CompanyID       uuid.NullUUID
	CompanyName     sql.NullString
	KraPin          sql.NullString
	Status          string
	PaymentStatus   string
	CurrencyCode    string
	Subtotal        string
	TaxAmount       string
	ShippingAmount  string
	DiscountAmount  string
	GrandTotal      string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	OrderNumber     sql.NullString
}

func (q *Queries) GetOrdersByGuestCheckoutId(ctx context.Context, guestCheckoutID uuid.NullUUID) ([]GetOrdersByGuestCheckoutIdRow, error) {
	rows, err := q.query(ctx, q.getOrdersByGuestCheckoutIdStmt, getOrdersByGuestCheckoutId, guestCheckoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrdersByGuestCheckoutIdRow{}
	for rows.Next() {
		var i GetOrdersByGuestCheckoutIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestCheckoutID,
			&i.CompanyID,
			&i.CompanyName,
			&i.KraPin,
			&i.Status,
			&i.PaymentStatus,
			&i.CurrencyCode,
			&i.Subtotal,
			&i.TaxAmount,
			&i.ShippingAmount,
			&i.DiscountAmount,
			&i.GrandTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserId = `-- name: GetOrdersByUserId :many
SELECT id, user_id,guest_checkout_id,  status, payment_status, total, created_at, updated_at, order_number
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetOrdersByUserIdRow struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	GuestCheckoutID uuid.NullUUID
	Status          string
	PaymentStatus   string
	Total           string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	OrderNumber     sql.NullString
}

func (q *Queries) GetOrdersByUserId(ctx context.Context, userID uuid.NullUUID) ([]GetOrdersByUserIdRow, error) {
	rows, err := q.query(ctx, q.getOrdersByUserIdStmt, getOrdersByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrdersByUserIdRow{}
	for rows.Next() {
		var i GetOrdersByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestCheckoutID,
			&i.Status,
			&i.PaymentStatus,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSales = `-- name: GetRecentSales :many
SELECT
    COALESCE(u.first_name || ' ' || u.last_name, g.first_name || ' ' || g.last_name)::varchar AS name,
    COALESCE(u.email, g.email) AS email,
    op.amount,
    COALESCE(SUBSTRING(u.first_name, 1, 1) || SUBSTRING(u.last_name, 1, 1),
             SUBSTRING(g.first_name, 1, 1) || SUBSTRING(g.last_name, 1, 1))::varchar AS fallback
FROM
    orders o
        LEFT JOIN
    users u ON o.user_id = u.id
        LEFT JOIN
    guest_checkouts g ON o.guest_checkout_id = g.id
        JOIN
    order_payments op ON o.id = op.order_id
ORDER BY
    o.created_at DESC
LIMIT 10
`

type GetRecentSalesRow struct {
	Name     string
	Email    string
	Amount   string
	Fallback string
}

func (q *Queries) GetRecentSales(ctx context.Context) ([]GetRecentSalesRow, error) {
	rows, err := q.query(ctx, q.getRecentSalesStmt, getRecentSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentSalesRow{}
	for rows.Next() {
		var i GetRecentSalesRow
		if err := rows.Scan(
			&i.Name,
			&i.Email,
			&i.Amount,
			&i.Fallback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesTrend = `-- name: GetSalesTrend :one
WITH sales_data AS (
    SELECT
        TO_CHAR(date_trunc('month', created_at), 'YYYY-MM') AS month,
        COALESCE(SUM(amount), 0) AS total_sales
    FROM
        order_payments
    WHERE
        payment_status_id = $1
    GROUP BY
        month
    ORDER BY
        month DESC
    LIMIT 2
)
SELECT
    COALESCE(MAX(total_sales), 0)::numeric AS current_month_sales,
    COALESCE(
            (SELECT total_sales FROM sales_data ORDER BY month DESC LIMIT 1 OFFSET 1),
            0
    )::numeric AS previous_month_sales
FROM sales_data
`

type GetSalesTrendRow struct {
	CurrentMonthSales  string
	PreviousMonthSales string
}

func (q *Queries) GetSalesTrend(ctx context.Context, paymentStatusID sql.NullInt32) (GetSalesTrendRow, error) {
	row := q.queryRow(ctx, q.getSalesTrendStmt, getSalesTrend, paymentStatusID)
	var i GetSalesTrendRow
	err := row.Scan(&i.CurrentMonthSales, &i.PreviousMonthSales)
	return i, err
}

const getTotalRevenueByPaymentStatus = `-- name: GetTotalRevenueByPaymentStatus :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total_revenue
FROM order_payments
WHERE payment_status_id = $1
`

// GetTotalRevenueByStatus gets the total revenue for orders with a specific payment status
func (q *Queries) GetTotalRevenueByPaymentStatus(ctx context.Context, paymentStatusID sql.NullInt32) (string, error) {
	row := q.queryRow(ctx, q.getTotalRevenueByPaymentStatusStmt, getTotalRevenueByPaymentStatus, paymentStatusID)
	var total_revenue string
	err := row.Scan(&total_revenue)
	return total_revenue, err
}

const getTotalRevenueForLastTwoMonths = `-- name: GetTotalRevenueForLastTwoMonths :one
WITH revenue_data AS (
    SELECT
        date_trunc('month', created_at) AS month,
        COALESCE(SUM(amount), 0)::numeric AS total_revenue
    FROM order_payments
    WHERE payment_status_id = $1
    GROUP BY month
    ORDER BY month DESC
    LIMIT 2
)
SELECT
    COALESCE(MAX(total_revenue), 0)::numeric AS current_month_revenue,
    COALESCE(
        (SELECT total_revenue FROM revenue_data ORDER BY month DESC OFFSET 1 LIMIT 1),
        0
    )::numeric AS previous_month_revenue
FROM revenue_data
`

type GetTotalRevenueForLastTwoMonthsRow struct {
	CurrentMonthRevenue  string
	PreviousMonthRevenue string
}

func (q *Queries) GetTotalRevenueForLastTwoMonths(ctx context.Context, paymentStatusID sql.NullInt32) (GetTotalRevenueForLastTwoMonthsRow, error) {
	row := q.queryRow(ctx, q.getTotalRevenueForLastTwoMonthsStmt, getTotalRevenueForLastTwoMonths, paymentStatusID)
	var i GetTotalRevenueForLastTwoMonthsRow
	err := row.Scan(&i.CurrentMonthRevenue, &i.PreviousMonthRevenue)
	return i, err
}

const getTotalSalesCurrentMonth = `-- name: GetTotalSalesCurrentMonth :one
SELECT
    COUNT(*) AS total_sales
FROM
    orders
WHERE
    created_at >= date_trunc('month', current_date)
  AND created_at < date_trunc('month', current_date) + interval '1 month'
`

func (q *Queries) GetTotalSalesCurrentMonth(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getTotalSalesCurrentMonthStmt, getTotalSalesCurrentMonth)
	var total_sales int64
	err := row.Scan(&total_sales)
	return total_sales, err
}

const getUserOrGuestCheckoutNameByOrderID = `-- name: GetUserOrGuestCheckoutNameByOrderID :one
SELECT
    u.first_name AS user_first_name,
    u.last_name AS user_last_name,
    u.phone_number AS user_phone_number,
    g.first_name AS guest_first_name,
    g.last_name AS guest_last_name,
    g.phone AS guest_phone,
    o.company_name,
    o.kra_pin
FROM orders o
LEFT JOIN users u ON o.user_id = u.id
LEFT JOIN guest_checkouts g ON o.guest_checkout_id = g.id
WHERE o.id = $1
`

type GetUserOrGuestCheckoutNameByOrderIDRow struct {
	UserFirstName   sql.NullString
	UserLastName    sql.NullString
	UserPhoneNumber sql.NullString
	GuestFirstName  sql.NullString
	GuestLastName   sql.NullString
	GuestPhone      sql.NullString
	CompanyName     sql.NullString
	KraPin          sql.NullString
}

func (q *Queries) GetUserOrGuestCheckoutNameByOrderID(ctx context.Context, id uuid.UUID) (GetUserOrGuestCheckoutNameByOrderIDRow, error) {
	row := q.queryRow(ctx, q.getUserOrGuestCheckoutNameByOrderIDStmt, getUserOrGuestCheckoutNameByOrderID, id)
	var i GetUserOrGuestCheckoutNameByOrderIDRow
	err := row.Scan(
		&i.UserFirstName,
		&i.UserLastName,
		&i.UserPhoneNumber,
		&i.GuestFirstName,
		&i.GuestLastName,
		&i.GuestPhone,
		&i.CompanyName,
		&i.KraPin,
	)
	return i, err
}

const updateOrderAmounts = `-- name: UpdateOrderAmounts :one
WITH vat_rate AS (
  SELECT vat_percentage / 100.0 AS rate
  FROM settings
  WHERE id = TRUE
),
updated_values AS (
  SELECT
    $1::uuid AS id,
    $2::numeric AS subtotal,
    $3::numeric AS tax_amount,
    $4::numeric AS shipping_amount,
    $5::numeric AS discount_amount,
    vr.rate,
    ($2 * vr.rate) AS vat_amount,
    ($2 + $3 + $4 + ($2 * vr.rate) - $5) AS grand_total
  FROM vat_rate vr
)
UPDATE orders o
SET
  subtotal = uv.subtotal,
  tax_amount = uv.tax_amount,
  shipping_amount = uv.shipping_amount,
  discount_amount = uv.discount_amount,
  vat_amount = uv.vat_amount,
  grand_total = uv.grand_total,
  updated_at = now()
FROM updated_values uv
WHERE o.id = uv.id
RETURNING
  o.subtotal,
  o.tax_amount,
  o.shipping_amount,
  o.discount_amount,
  o.vat_amount,
  o.grand_total
`

type UpdateOrderAmountsParams struct {
	Column1 uuid.UUID
	Column2 string
	Column3 string
	Column4 string
	Column5 string
}

type UpdateOrderAmountsRow struct {
	Subtotal       string
	TaxAmount      string
	ShippingAmount string
	DiscountAmount string
	VatAmount      string
	GrandTotal     string
}

func (q *Queries) UpdateOrderAmounts(ctx context.Context, arg UpdateOrderAmountsParams) (UpdateOrderAmountsRow, error) {
	row := q.queryRow(ctx, q.updateOrderAmountsStmt, updateOrderAmounts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i UpdateOrderAmountsRow
	err := row.Scan(
		&i.Subtotal,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.VatAmount,
		&i.GrandTotal,
	)
	return i, err
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :exec
UPDATE orders
SET payment_status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderPaymentStatusParams struct {
	ID            uuid.UUID
	PaymentStatus string
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) error {
	_, err := q.exec(ctx, q.updateOrderPaymentStatusStmt, updateOrderPaymentStatus, arg.ID, arg.PaymentStatus)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.exec(ctx, q.updateOrderStatusStmt, updateOrderStatus, arg.ID, arg.Status)
	return err
}
