// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: order_items.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW(), NOW())
RETURNING id
`

type CreateOrderItemParams struct {
	OrderID   uuid.NullUUID
	ProductID uuid.NullUUID
	Quantity  int32
	Price     string
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createOrderItemOption = `-- name: CreateOrderItemOption :exec
INSERT INTO order_item_options (order_item_id, option_type, option_value, additional_price)
VALUES ($1, $2, $3, $4)
`

type CreateOrderItemOptionParams struct {
	OrderItemID     uuid.NullUUID
	OptionType      string
	OptionValue     string
	AdditionalPrice sql.NullString
}

func (q *Queries) CreateOrderItemOption(ctx context.Context, arg CreateOrderItemOptionParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItemOption,
		arg.OrderItemID,
		arg.OptionType,
		arg.OptionValue,
		arg.AdditionalPrice,
	)
	return err
}

const getOrderItemsByOrderId = `-- name: GetOrderItemsByOrderId :many
SELECT id, order_id, product_id, quantity, price, created_at, updated_at
FROM order_items
WHERE order_id = $1
`

func (q *Queries) GetOrderItemsByOrderId(ctx context.Context, orderID uuid.NullUUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
