// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: payments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO order_payments (order_id, payment_id, payment_method_id, payment_status_id, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, payment_id, payment_method_id, payment_status_id, amount, created_at
`

type CreatePaymentParams struct {
	OrderID         uuid.NullUUID
	PaymentID       string
	PaymentMethodID sql.NullInt32
	PaymentStatusID sql.NullInt32
	Amount          string
}

type CreatePaymentRow struct {
	ID              uuid.UUID
	OrderID         uuid.NullUUID
	PaymentID       string
	PaymentMethodID sql.NullInt32
	PaymentStatusID sql.NullInt32
	Amount          string
	CreatedAt       sql.NullTime
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.PaymentID,
		arg.PaymentMethodID,
		arg.PaymentStatusID,
		arg.Amount,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.PaymentMethodID,
		&i.PaymentStatusID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getAllPayments = `-- name: GetAllPayments :many
SELECT id, order_id, payment_id, payment_method_id, payment_status_id, amount, created_at
FROM order_payments
`

type GetAllPaymentsRow struct {
	ID              uuid.UUID
	OrderID         uuid.NullUUID
	PaymentID       string
	PaymentMethodID sql.NullInt32
	PaymentStatusID sql.NullInt32
	Amount          string
	CreatedAt       sql.NullTime
}

func (q *Queries) GetAllPayments(ctx context.Context) ([]GetAllPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPaymentsRow
	for rows.Next() {
		var i GetAllPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentID,
			&i.PaymentMethodID,
			&i.PaymentStatusID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsByOrderID = `-- name: GetPaymentsByOrderID :many
SELECT id, order_id, payment_id, payment_method_id, payment_status_id, amount, created_at
FROM order_payments
WHERE order_id = $1
`

type GetPaymentsByOrderIDRow struct {
	ID              uuid.UUID
	OrderID         uuid.NullUUID
	PaymentID       string
	PaymentMethodID sql.NullInt32
	PaymentStatusID sql.NullInt32
	Amount          string
	CreatedAt       sql.NullTime
}

func (q *Queries) GetPaymentsByOrderID(ctx context.Context, orderID uuid.NullUUID) ([]GetPaymentsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentsByOrderIDRow
	for rows.Next() {
		var i GetPaymentsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentID,
			&i.PaymentMethodID,
			&i.PaymentStatusID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE order_payments
SET payment_status_id = $1, updated_at = NOW()
WHERE payment_id = $2
`

type UpdatePaymentStatusParams struct {
	PaymentStatusID sql.NullInt32
	PaymentID       string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.PaymentStatusID, arg.PaymentID)
	return err
}
