// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: product_sizes.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProductSize = `-- name: CreateProductSize :one
INSERT INTO product_sizes (product_id, size, additional_price)
VALUES ($1, $2, $3)
    RETURNING id, product_id, size, additional_price, created_at, updated_at
`

type CreateProductSizeParams struct {
	ProductID       uuid.NullUUID
	Size            string
	AdditionalPrice sql.NullString
}

func (q *Queries) CreateProductSize(ctx context.Context, arg CreateProductSizeParams) (ProductSize, error) {
	row := q.db.QueryRowContext(ctx, createProductSize, arg.ProductID, arg.Size, arg.AdditionalPrice)
	var i ProductSize
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductSize = `-- name: DeleteProductSize :exec
DELETE FROM product_sizes
WHERE id = $1
`

func (q *Queries) DeleteProductSize(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductSize, id)
	return err
}

const getAllSizes = `-- name: GetAllSizes :many
SELECT DISTINCT id, size
FROM product_sizes
ORDER BY size
`

type GetAllSizesRow struct {
	ID   uuid.UUID
	Size string
}

func (q *Queries) GetAllSizes(ctx context.Context) ([]GetAllSizesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSizesRow
	for rows.Next() {
		var i GetAllSizesRow
		if err := rows.Scan(&i.ID, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableSizesByParentCategoryID = `-- name: GetAvailableSizesByParentCategoryID :many
WITH RECURSIVE category_tree AS (
    SELECT c.id
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
)
SELECT DISTINCT ps.size
FROM products p
         JOIN product_sizes ps ON p.id = ps.product_id
         JOIN category_tree ct ON p.category_id = ct.id
ORDER BY ps.size
`

func (q *Queries) GetAvailableSizesByParentCategoryID(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableSizesByParentCategoryID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var size string
		if err := rows.Scan(&size); err != nil {
			return nil, err
		}
		items = append(items, size)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductSizeByID = `-- name: GetProductSizeByID :one
 -- product_id UUID REFERENCES products(id) ON DELETE CASCADE,
 -- size VARCHAR(50) NOT NULL,
 -- additional_price DECIMAL(10, 2) DEFAULT 0,
 -- created_at TIMESTAMPTZ DEFAULT NOW(),
 -- updated_at TIMESTAMPTZ DEFAULT NOW()



SELECT id, product_id, size, additional_price, created_at, updated_at
FROM product_sizes
WHERE id = $1
`

// id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
func (q *Queries) GetProductSizeByID(ctx context.Context, id uuid.UUID) (ProductSize, error) {
	row := q.db.QueryRowContext(ctx, getProductSizeByID, id)
	var i ProductSize
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductSizesByProductID = `-- name: ListProductSizesByProductID :many
SELECT id, product_id, size, additional_price, created_at, updated_at
FROM product_sizes
WHERE product_id = $1
ORDER BY created_at
`

func (q *Queries) ListProductSizesByProductID(ctx context.Context, productID uuid.NullUUID) ([]ProductSize, error) {
	rows, err := q.db.QueryContext(ctx, listProductSizesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductSize
	for rows.Next() {
		var i ProductSize
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Size,
			&i.AdditionalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductSize = `-- name: UpdateProductSize :one
UPDATE product_sizes
SET size = $2, additional_price = $3, updated_at = NOW()
WHERE id = $1
    RETURNING id, product_id, size, additional_price, created_at, updated_at
`

type UpdateProductSizeParams struct {
	ID              uuid.UUID
	Size            string
	AdditionalPrice sql.NullString
}

func (q *Queries) UpdateProductSize(ctx context.Context, arg UpdateProductSizeParams) (ProductSize, error) {
	row := q.db.QueryRowContext(ctx, updateProductSize, arg.ID, arg.Size, arg.AdditionalPrice)
	var i ProductSize
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
