// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: product_variants.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (product_id, variant_name, variant_value, additional_price)
VALUES ($1, $2, $3, $4)
    RETURNING id, product_id, variant_name, variant_value, additional_price, created_at, updated_at
`

type CreateProductVariantParams struct {
	ProductID       uuid.NullUUID
	VariantName     string
	VariantValue    string
	AdditionalPrice sql.NullString
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant,
		arg.ProductID,
		arg.VariantName,
		arg.VariantValue,
		arg.AdditionalPrice,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantName,
		&i.VariantValue,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variants
WHERE id = $1
`

func (q *Queries) DeleteProductVariant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductVariant, id)
	return err
}

const getProductVariantByID = `-- name: GetProductVariantByID :one
SELECT id, product_id, variant_name, variant_value, additional_price, created_at, updated_at
FROM product_variants
WHERE id = $1
`

func (q *Queries) GetProductVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantByID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantName,
		&i.VariantValue,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductVariantsByProductID = `-- name: ListProductVariantsByProductID :many
SELECT id, product_id, variant_name, variant_value, additional_price, created_at, updated_at
FROM product_variants
WHERE product_id = $1
ORDER BY variant_name
`

func (q *Queries) ListProductVariantsByProductID(ctx context.Context, productID uuid.NullUUID) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VariantName,
			&i.VariantValue,
			&i.AdditionalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variants
SET variant_name = $2, variant_value = $3, additional_price = $4, updated_at = NOW()
WHERE id = $1
    RETURNING id, product_id, variant_name, variant_value, additional_price, created_at, updated_at
`

type UpdateProductVariantParams struct {
	ID              uuid.UUID
	VariantName     string
	VariantValue    string
	AdditionalPrice sql.NullString
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariant,
		arg.ID,
		arg.VariantName,
		arg.VariantValue,
		arg.AdditionalPrice,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantName,
		&i.VariantValue,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
