// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: products.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const activateProductsBySlugs = `-- name: ActivateProductsBySlugs :exec
UPDATE products
SET status = 'active', updated_by = $2
WHERE slug = ANY($1::text[])
`

type ActivateProductsBySlugsParams struct {
	Column1   []string
	UpdatedBy uuid.NullUUID
}

func (q *Queries) ActivateProductsBySlugs(ctx context.Context, arg ActivateProductsBySlugsParams) error {
	_, err := q.db.ExecContext(ctx, activateProductsBySlugs, pq.Array(arg.Column1), arg.UpdatedBy)
	return err
}

const archiveProductByID = `-- name: ArchiveProductByID :exec
UPDATE products
SET status = 'archived', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveProductByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, archiveProductByID, id)
	return err
}

const archiveProductsBySlugs = `-- name: ArchiveProductsBySlugs :exec
UPDATE products
SET status = 'archived', updated_by = $2
WHERE slug = ANY($1::text[])
`

type ArchiveProductsBySlugsParams struct {
	Column1   []string
	UpdatedBy uuid.NullUUID
}

func (q *Queries) ArchiveProductsBySlugs(ctx context.Context, arg ArchiveProductsBySlugsParams) error {
	_, err := q.db.ExecContext(ctx, archiveProductsBySlugs, pq.Array(arg.Column1), arg.UpdatedBy)
	return err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) AS count
FROM products WHERE status = 'active'
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByParentCategoryID = `-- name: CountProductsByParentCategoryID :one
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id,
        c.position
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT
        c2.id,
        c2.name,
        c2.parent_id,
        c2.position
    FROM categories c2
             INNER JOIN category_hierarchy ch ON c2.parent_id = ch.id
)
SELECT COUNT(*) AS count
FROM products p
WHERE p.category_id IN (SELECT ch.id FROM category_hierarchy ch)
AND p.status = 'active'
`

func (q *Queries) CountProductsByParentCategoryID(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByParentCategoryID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
WITH rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
INSERT INTO products (
    id, name, description, stock, category_id, created_by, updated_by,
    part_number, meta_title, meta_description, meta_keywords,
    status, usd_price, price_per_unit
)
VALUES (
           gen_random_uuid(),
           $1, $2, $3, $4, $5, $6,
           $7, $8, $9, $10,
           $11,
           $12 / (SELECT rate_to_kes FROM rate),
              $13 / (SELECT rate_to_kes FROM rate)
       )
RETURNING id, name, description, stock, category_id, created_at, updated_at, created_by, updated_by, featured, search_keyword, part_number, meta_title, meta_description, meta_keywords, slug, status, usd_price, price_per_unit, valid_from, valid_to
`

type CreateProductParams struct {
	Name            string
	Description     sql.NullString
	Stock           sql.NullInt32
	CategoryID      uuid.UUID
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
	PartNumber      string
	MetaTitle       sql.NullString
	MetaDescription sql.NullString
	MetaKeywords    sql.NullString
	Status          string
	RateToKes       string
	RateToKes_2     string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Stock,
		arg.CategoryID,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.PartNumber,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
		arg.Status,
		arg.RateToKes,
		arg.RateToKes_2,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Featured,
		&i.SearchKeyword,
		&i.PartNumber,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.Slug,
		&i.Status,
		&i.UsdPrice,
		&i.PricePerUnit,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const deleteProductByID = `-- name: DeleteProductByID :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProductByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductByID, id)
	return err
}

const deleteProductImagesByProductID = `-- name: DeleteProductImagesByProductID :exec
DELETE FROM product_images WHERE product_id = $1
`

func (q *Queries) DeleteProductImagesByProductID(ctx context.Context, productID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductImagesByProductID, productID)
	return err
}

const deleteProductSpecificationsByProductID = `-- name: DeleteProductSpecificationsByProductID :exec
DELETE FROM product_specifications WHERE product_id = $1
`

func (q *Queries) DeleteProductSpecificationsByProductID(ctx context.Context, productID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductSpecificationsByProductID, productID)
	return err
}

const deleteProductsBySlugs = `-- name: DeleteProductsBySlugs :exec
DELETE FROM products
WHERE slug = ANY($1::text[])
`

func (q *Queries) DeleteProductsBySlugs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.ExecContext(ctx, deleteProductsBySlugs, pq.Array(dollar_1))
	return err
}

const draftProductsBySlugs = `-- name: DraftProductsBySlugs :exec
UPDATE products
SET status = 'draft', updated_by = $2
WHERE slug = ANY($1::text[])
`

type DraftProductsBySlugsParams struct {
	Column1   []string
	UpdatedBy uuid.NullUUID
}

func (q *Queries) DraftProductsBySlugs(ctx context.Context, arg DraftProductsBySlugsParams) error {
	_, err := q.db.ExecContext(ctx, draftProductsBySlugs, pq.Array(arg.Column1), arg.UpdatedBy)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, usd_price, stock, category_id, created_at, updated_at, status, created_by, updated_by, featured, search_keyword, slug
FROM products
WHERE id = $1
`

type GetProductByIDRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	UsdPrice      string
	Stock         sql.NullInt32
	CategoryID    uuid.UUID
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Status        string
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
	Featured      sql.NullBool
	SearchKeyword interface{}
	Slug          string
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UsdPrice,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Featured,
		&i.SearchKeyword,
		&i.Slug,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.name, p.description, p.usd_price, p.stock, c.name AS category_name, p.created_at, p.updated_at, p.status, p.created_by, p.updated_by, p.featured, p.search_keyword, p.slug
FROM products p
         JOIN categories c ON p.category_id = c.id
WHERE p.slug = $1
`

type GetProductBySlugRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	UsdPrice      string
	Stock         sql.NullInt32
	CategoryName  string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Status        string
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
	Featured      sql.NullBool
	SearchKeyword interface{}
	Slug          string
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UsdPrice,
		&i.Stock,
		&i.CategoryName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Featured,
		&i.SearchKeyword,
		&i.Slug,
	)
	return i, err
}

const getProductIDsBySlugs = `-- name: GetProductIDsBySlugs :many
SELECT
    id
FROM
    products
WHERE
    slug = ANY($1::text[])
`

func (q *Queries) GetProductIDsBySlugs(ctx context.Context, dollar_1 []string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getProductIDsBySlugs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductPricingByProductID = `-- name: GetProductPricingByProductID :one
WITH rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
SELECT
    p.id,
    p.name,
    p.description,
    (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric AS price_in_kes,
    COALESCE(d.discount_percentage, 0) AS discount_percent,
    COALESCE(pi.image_url, '')::TEXT AS imageUrl
FROM
    products p
        LEFT JOIN LATERAL (
        SELECT
            pi.image_url
        FROM
            product_images pi
        WHERE
            pi.product_id = p.id
        ORDER BY
            pi.position ASC
        LIMIT 1
        ) pi ON TRUE
        LEFT JOIN discounts d ON d.product_id = p.id
WHERE
    p.id = $1
LIMIT 1
`

type GetProductPricingByProductIDRow struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	PriceInKes      string
	DiscountPercent string
	Imageurl        string
}

func (q *Queries) GetProductPricingByProductID(ctx context.Context, id uuid.UUID) (GetProductPricingByProductIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductPricingByProductID, id)
	var i GetProductPricingByProductIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceInKes,
		&i.DiscountPercent,
		&i.Imageurl,
	)
	return i, err
}

const getProductSpecsByID = `-- name: GetProductSpecsByID :one
SELECT
    p.description,
    json_agg(
            json_build_object(
                    'name', ps.spec_name,
                    'value', ps.spec_value
            )
    ) AS specs
FROM
    products p
        JOIN
    product_specifications ps ON ps.product_id = p.id
WHERE
    p.id = $1
GROUP BY
    p.description
`

type GetProductSpecsByIDRow struct {
	Description sql.NullString
	Specs       json.RawMessage
}

func (q *Queries) GetProductSpecsByID(ctx context.Context, id uuid.UUID) (GetProductSpecsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductSpecsByID, id)
	var i GetProductSpecsByIDRow
	err := row.Scan(&i.Description, &i.Specs)
	return i, err
}

const getProductsByCategoryID = `-- name: GetProductsByCategoryID :many
SELECT id, name, description, usd_price, stock, category_id, created_at, updated_at, status, created_by, updated_by, featured, search_keyword
FROM products
WHERE category_id = $1
ORDER BY name
`

type GetProductsByCategoryIDRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	UsdPrice      string
	Stock         sql.NullInt32
	CategoryID    uuid.UUID
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Status        string
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
	Featured      sql.NullBool
	SearchKeyword interface{}
}

func (q *Queries) GetProductsByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]GetProductsByCategoryIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCategoryIDRow
	for rows.Next() {
		var i GetProductsByCategoryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UsdPrice,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Featured,
			&i.SearchKeyword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByParentCategoryID = `-- name: GetProductsByParentCategoryID :many
WITH RECURSIVE category_hierarchy AS (
    SELECT
        c.id,
        c.name,
        c.parent_id,
        c.position
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT
        c2.id,
        c2.name,
        c2.parent_id,
        c2.position
    FROM categories c2
             INNER JOIN category_hierarchy ch ON c2.parent_id = ch.id
)
SELECT
    p.id, p.name, p.description, p.usd_price, p.stock, p.created_at, p.updated_at, p.status,
    p.created_by, p.updated_by, p.featured, p.search_keyword, p.slug,
    c.name AS category_name
FROM products p
         JOIN categories c ON p.category_id = c.id
WHERE p.category_id IN (SELECT ch.id FROM category_hierarchy ch)
AND p.status = 'active'
LIMIT $2 OFFSET $3
`

type GetProductsByParentCategoryIDParams struct {
	ID     uuid.UUID
	Limit  int32
	Offset int32
}

type GetProductsByParentCategoryIDRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	UsdPrice      string
	Stock         sql.NullInt32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Status        string
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
	Featured      sql.NullBool
	SearchKeyword interface{}
	Slug          string
	CategoryName  string
}

func (q *Queries) GetProductsByParentCategoryID(ctx context.Context, arg GetProductsByParentCategoryIDParams) ([]GetProductsByParentCategoryIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByParentCategoryID, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByParentCategoryIDRow
	for rows.Next() {
		var i GetProductsByParentCategoryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UsdPrice,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Featured,
			&i.SearchKeyword,
			&i.Slug,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getV2ProductDetailBySlug = `-- name: GetV2ProductDetailBySlug :one
WITH rate AS (
    SELECT COALESCE(
                   (SELECT rate_to_kes
                    FROM exchange_rates
                    WHERE currency_code = 'USD'
                      AND (valid_to IS NULL OR valid_to >= NOW())
                      AND valid_from <= NOW()
                    ORDER BY valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
),
     product_cte AS (
         SELECT
             p.id,
             p.name,
             p.description,
             (p.usd_price * r.rate_to_kes)::numeric AS price_in_kes,
             (p.price_per_unit * r.rate_to_kes)::numeric AS price_per_unit_in_kes,
             r.rate_to_kes AS exchange_rate,
             p.slug,
             p.stock,
             p.part_number,
             p.category_id,
             c.parent_id AS parent_category_id,
             p.meta_description,
             p.meta_keywords,
             p.meta_title,
             p.status,
             (NOW() BETWEEN p.valid_from AND COALESCE(p.valid_to, 'infinity'::timestamp)) AS is_valid
         FROM
             products p
                 JOIN categories c ON p.category_id = c.id,
             rate r
         WHERE
             p.slug = $1
     ),
     specs_cte AS (
         SELECT
             ps.product_id,
             json_agg(json_build_object('name', ps.spec_name, 'value', ps.spec_value)) AS specifications
         FROM
             product_specifications ps
                 JOIN product_cte p ON ps.product_id = p.id
         GROUP BY
             ps.product_id
     ),
     images_cte AS (
         SELECT
             pi.product_id,
             json_agg(json_build_object('url', pi.image_url) ORDER BY pi.position) AS images
         FROM
             product_images pi
                 JOIN product_cte p ON pi.product_id = p.id
         GROUP BY
             pi.product_id
     ),
     metafields_cte AS (
         SELECT
             ptav.product_id,
             json_agg(json_build_object('name', pa.name, 'value', pav.value)) AS metafields
         FROM
             product_to_attribute_values ptav
                 JOIN product_attribute_values pav ON ptav.attribute_value_id = pav.id
                 JOIN product_attributes pa ON pav.attribute_id = pa.id
                 JOIN product_cte p ON ptav.product_id = p.id
         GROUP BY
             ptav.product_id
     )
SELECT
    p.name,
    p.description,
    p.price_in_kes::text AS price,
    p.price_per_unit_in_kes::text AS price_per_unit,
    p.exchange_rate::numeric AS exchange_rate,
    CAST(p.stock AS INTEGER) AS stock,
    p.part_number,
    p.slug,
    p.meta_title,
    p.meta_description,
    p.meta_keywords,
    p.category_id,
    p.parent_category_id,
    p.status,
    p.is_valid::boolean AS is_valid,
    COALESCE(s.specifications, '[]'::json) AS specifications,
    COALESCE(i.images, '[]'::json) AS images,
    COALESCE(m.metafields, '[]'::json) AS product_metafields
FROM
    product_cte p
        LEFT JOIN
    specs_cte s ON p.id = s.product_id
        LEFT JOIN
    images_cte i ON p.id = i.product_id
        LEFT JOIN
    metafields_cte m ON p.id = m.product_id
`

type GetV2ProductDetailBySlugRow struct {
	Name              string
	Description       sql.NullString
	Price             string
	PricePerUnit      string
	ExchangeRate      string
	Stock             int32
	PartNumber        string
	Slug              string
	MetaTitle         sql.NullString
	MetaDescription   sql.NullString
	MetaKeywords      sql.NullString
	CategoryID        uuid.UUID
	ParentCategoryID  uuid.NullUUID
	Status            string
	IsValid           bool
	Specifications    json.RawMessage
	Images            json.RawMessage
	ProductMetafields json.RawMessage
}

func (q *Queries) GetV2ProductDetailBySlug(ctx context.Context, slug string) (GetV2ProductDetailBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getV2ProductDetailBySlug, slug)
	var i GetV2ProductDetailBySlugRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Price,
		&i.PricePerUnit,
		&i.ExchangeRate,
		&i.Stock,
		&i.PartNumber,
		&i.Slug,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.CategoryID,
		&i.ParentCategoryID,
		&i.Status,
		&i.IsValid,
		&i.Specifications,
		&i.Images,
		&i.ProductMetafields,
	)
	return i, err
}

const getV2Products = `-- name: GetV2Products :many
WITH first_image AS (
    SELECT DISTINCT ON (product_id) product_id, image_url
    FROM product_images
    ORDER BY product_id, position
),
     rate AS (
         SELECT COALESCE(
                        (SELECT rate_to_kes
                         FROM exchange_rates
                         WHERE currency_code = 'USD'
                           AND (valid_to IS NULL OR valid_to >= NOW())
                           AND valid_from <= NOW()
                         ORDER BY valid_from DESC
                         LIMIT 1),
                        135) AS rate_to_kes
     )
SELECT
    p.name,
    (p.usd_price * (SELECT rate_to_kes FROM rate))::numeric AS price_in_kes,
    p.status,
    COALESCE(fi.image_url, '') AS imageURL,
    COALESCE(d.discount_percentage, 0) AS discount,
    p.slug,
    p.created_at AS createdAt,
    EXISTS (
        SELECT 1
        FROM promotion_products pp
        WHERE pp.product_id = p.id
    ) AS inPromotion,
    (
        SELECT COALESCE(SUM(oi.quantity), 0)
        FROM order_items oi
                 JOIN orders o ON oi.order_id = o.id
        WHERE oi.product_id = p.id
          AND o.status = 'pending'
    )::int AS totalSales,
    p.part_number AS partNumber,
    pc.name AS categoryName
FROM products p
         LEFT JOIN first_image fi ON fi.product_id = p.id
         LEFT JOIN discounts d ON d.product_id = p.id AND d.start_date <= NOW() AND d.end_date >= NOW()
         LEFT JOIN categories c ON p.category_id = c.id
         LEFT JOIN categories pc ON c.parent_id = pc.id
ORDER BY p.created_at DESC
`

type GetV2ProductsRow struct {
	Name         string
	PriceInKes   string
	Status       string
	Imageurl     string
	Discount     string
	Slug         string
	Createdat    sql.NullTime
	Inpromotion  bool
	Totalsales   int32
	Partnumber   string
	Categoryname sql.NullString
}

func (q *Queries) GetV2Products(ctx context.Context) ([]GetV2ProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getV2Products)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetV2ProductsRow
	for rows.Next() {
		var i GetV2ProductsRow
		if err := rows.Scan(
			&i.Name,
			&i.PriceInKes,
			&i.Status,
			&i.Imageurl,
			&i.Discount,
			&i.Slug,
			&i.Createdat,
			&i.Inpromotion,
			&i.Totalsales,
			&i.Partnumber,
			&i.Categoryname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, usd_price, stock, category_id, created_at, updated_at, status, created_by, updated_by, featured, search_keyword, slug
FROM products
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

type ListProductsRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	UsdPrice      string
	Stock         sql.NullInt32
	CategoryID    uuid.UUID
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Status        string
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
	Featured      sql.NullBool
	SearchKeyword interface{}
	Slug          string
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UsdPrice,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Featured,
			&i.SearchKeyword,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
WITH RECURSIVE category_hierarchy AS (
    SELECT
        id,
        name,
        parent_id
    FROM
        categories
    WHERE
        name ILIKE '%' || $1 || '%'
    UNION ALL
    SELECT
        c.id,
        c.name,
        c.parent_id
    FROM
        categories c
            INNER JOIN category_hierarchy ch ON c.parent_id = ch.id
)
SELECT DISTINCT ON (p.id)
    p.id,
    p.name,
    p.description,
    p.usd_price,
    p.stock,
    p.category_id,
    p.created_at,
    p.updated_at,
    p.status,
    p.created_by,
    p.updated_by,
    p.featured,
    p.search_keyword,
    p.slug
FROM
    products p
        LEFT JOIN categories c ON p.category_id = c.id
        LEFT JOIN category_hierarchy ch ON p.category_id = ch.id
WHERE
    (
        p.name ILIKE '%' || $1 || '%' OR
        p.description ILIKE '%' || $1 || '%' OR
        COALESCE(c.name, '') ILIKE '%' || $1 || '%' OR
        p.search_keyword @@ plainto_tsquery('english', $1) OR
        ch.id IS NOT NULL
        )
  AND p.status = 'active'
ORDER BY
    p.id,
    ts_rank(p.search_keyword, plainto_tsquery('english', $1)) DESC,
    p.created_at DESC
`

type SearchProductsRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	UsdPrice      string
	Stock         sql.NullInt32
	CategoryID    uuid.UUID
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Status        string
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
	Featured      sql.NullBool
	SearchKeyword interface{}
	Slug          string
}

func (q *Queries) SearchProducts(ctx context.Context, dollar_1 sql.NullString) ([]SearchProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UsdPrice,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Featured,
			&i.SearchKeyword,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET status = 'archived', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
WITH rate AS (
    SELECT COALESCE(
                   (SELECT er.rate_to_kes
                    FROM exchange_rates er
                    WHERE er.currency_code = 'USD'
                      AND (er.valid_to IS NULL OR er.valid_to >= NOW())
                      AND er.valid_from <= NOW()
                    ORDER BY er.valid_from DESC
                    LIMIT 1),
                   135) AS rate_to_kes
)
UPDATE products p
SET
    name = $1,
    description = $2,
    stock = $3,
    category_id = $4,
    updated_by = $5,
    part_number = $6,
    meta_title = $7,
    meta_description = $8,
    meta_keywords = $9,
    status = $10,
    usd_price = $11 / (SELECT rate_to_kes FROM rate),
    price_per_unit = $12 / (SELECT rate_to_kes FROM rate),
    updated_at = NOW()
WHERE p.id = $13
`

type UpdateProductParams struct {
	Name            string
	Description     sql.NullString
	Stock           sql.NullInt32
	CategoryID      uuid.UUID
	UpdatedBy       uuid.NullUUID
	PartNumber      string
	MetaTitle       sql.NullString
	MetaDescription sql.NullString
	MetaKeywords    sql.NullString
	Status          string
	RateToKes       string
	RateToKes_2     string
	ID              uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Stock,
		arg.CategoryID,
		arg.UpdatedBy,
		arg.PartNumber,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
		arg.Status,
		arg.RateToKes,
		arg.RateToKes_2,
		arg.ID,
	)
	return err
}
