// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: product_analytics.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getBestSellerProducts = `-- name: GetBestSellerProducts :many
SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.stock,
    p.category_id,
    p.created_at,
    p.updated_at,
    p.is_active,
    p.featured,
    SUM(oi.quantity) AS total_sold
FROM
    products p
        JOIN
    order_items oi ON p.id = oi.product_id
GROUP BY
    p.id
ORDER BY
    total_sold DESC
LIMIT $1
`

type GetBestSellerProductsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       sql.NullInt32
	CategoryID  uuid.NullUUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	IsActive    sql.NullBool
	Featured    sql.NullBool
	TotalSold   int64
}

func (q *Queries) GetBestSellerProducts(ctx context.Context, limit int32) ([]GetBestSellerProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBestSellerProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBestSellerProductsRow
	for rows.Next() {
		var i GetBestSellerProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.Featured,
			&i.TotalSold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturedProducts = `-- name: GetFeaturedProducts :many
SELECT
    id,
    name,
    description,
    price,
    stock,
    category_id,
    created_at,
    updated_at,
    is_active,
    featured
FROM
    products
WHERE
    featured = true
ORDER BY
    created_at DESC
LIMIT $1
`

type GetFeaturedProductsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       sql.NullInt32
	CategoryID  uuid.NullUUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	IsActive    sql.NullBool
	Featured    sql.NullBool
}

func (q *Queries) GetFeaturedProducts(ctx context.Context, limit int32) ([]GetFeaturedProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeaturedProductsRow
	for rows.Next() {
		var i GetFeaturedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.Featured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewArrivalProducts = `-- name: GetNewArrivalProducts :many
SELECT
    id,
    name,
    description,
    price,
    stock,
    category_id,
    created_at,
    updated_at,
    is_active,
    featured
FROM
    products
WHERE
    is_active = true
  AND created_at >= NOW() - INTERVAL '30 days'
ORDER BY
    created_at DESC
LIMIT $1
`

type GetNewArrivalProductsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       sql.NullInt32
	CategoryID  uuid.NullUUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	IsActive    sql.NullBool
	Featured    sql.NullBool
}

func (q *Queries) GetNewArrivalProducts(ctx context.Context, limit int32) ([]GetNewArrivalProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNewArrivalProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewArrivalProductsRow
	for rows.Next() {
		var i GetNewArrivalProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.Featured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
