// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: product_attributes.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProductAttribute = `-- name: CreateProductAttribute :one
INSERT INTO product_attributes (name, attribute_type)
VALUES ($1, $2)
RETURNING id
`

type CreateProductAttributeParams struct {
	Name          string
	AttributeType AttributeTypeEnum
}

func (q *Queries) CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createProductAttribute, arg.Name, arg.AttributeType)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createProductAttributeValue = `-- name: CreateProductAttributeValue :one
INSERT INTO product_attribute_values (attribute_id, value, hex_value, category_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateProductAttributeValueParams struct {
	AttributeID uuid.NullUUID
	Value       string
	HexValue    sql.NullString
	CategoryID  uuid.NullUUID
}

func (q *Queries) CreateProductAttributeValue(ctx context.Context, arg CreateProductAttributeValueParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createProductAttributeValue,
		arg.AttributeID,
		arg.Value,
		arg.HexValue,
		arg.CategoryID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createProductToAttributeValue = `-- name: CreateProductToAttributeValue :exec
INSERT INTO product_to_attribute_values (
     product_id, attribute_value_id
) VALUES (
              $1, $2
         )
`

type CreateProductToAttributeValueParams struct {
	ProductID        uuid.NullUUID
	AttributeValueID uuid.NullUUID
}

func (q *Queries) CreateProductToAttributeValue(ctx context.Context, arg CreateProductToAttributeValueParams) error {
	_, err := q.db.ExecContext(ctx, createProductToAttributeValue, arg.ProductID, arg.AttributeValueID)
	return err
}
