// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: product_images.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, image_url)
VALUES ($1, $2)
    RETURNING id, product_id, image_url, created_at, updated_at, position
`

type CreateProductImageParams struct {
	ProductID uuid.NullUUID
	ImageUrl  string
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, createProductImage, arg.ProductID, arg.ImageUrl)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images
WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductImage, id)
	return err
}

const getImageKeysByProductID = `-- name: GetImageKeysByProductID :many
SELECT image_url FROM product_images WHERE product_id = $1
`

func (q *Queries) GetImageKeysByProductID(ctx context.Context, productID uuid.NullUUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getImageKeysByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_url string
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductImageByID = `-- name: GetProductImageByID :one
SELECT id, product_id, image_url, created_at, updated_at, position
FROM product_images
WHERE id = $1
`

func (q *Queries) GetProductImageByID(ctx context.Context, id uuid.UUID) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, getProductImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
	)
	return i, err
}

const listProductImagesByProductID = `-- name: ListProductImagesByProductID :many
SELECT id, product_id, image_url, created_at, updated_at, position
FROM product_images
WHERE product_id = $1
ORDER BY position
`

func (q *Queries) ListProductImagesByProductID(ctx context.Context, productID uuid.NullUUID) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, listProductImagesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductImage = `-- name: UpdateProductImage :one
UPDATE product_images
SET image_url = $2, updated_at = NOW()
WHERE id = $1
    RETURNING id, product_id, image_url, created_at, updated_at, position
`

type UpdateProductImageParams struct {
	ID       uuid.UUID
	ImageUrl string
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, updateProductImage, arg.ID, arg.ImageUrl)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
	)
	return i, err
}

const updateProductImages = `-- name: UpdateProductImages :exec
WITH updated_images AS (
    SELECT pi.id,
           pi.image_url,
           row_number() OVER (ORDER BY array_position($2::text[], pi.image_url)) AS new_position
    FROM product_images pi
    WHERE pi.product_id = $1 AND pi.image_url = ANY($2::text[])
)
UPDATE product_images
SET position = updated_images.new_position
FROM updated_images
WHERE product_images.id = updated_images.id
`

type UpdateProductImagesParams struct {
	ProductID uuid.NullUUID
	Column2   []string
}

func (q *Queries) UpdateProductImages(ctx context.Context, arg UpdateProductImagesParams) error {
	_, err := q.db.ExecContext(ctx, updateProductImages, arg.ProductID, pq.Array(arg.Column2))
	return err
}
