// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: product_colors.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProductColor = `-- name: CreateProductColor :one
INSERT INTO product_colors (product_id, color_id)
VALUES ($1, (SELECT id FROM colors WHERE color_name = $2))
RETURNING id, product_id, color_id, created_at, updated_at
`

type CreateProductColorParams struct {
	ProductID uuid.NullUUID
	ColorName string
}

type CreateProductColorRow struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	ColorID   uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateProductColor(ctx context.Context, arg CreateProductColorParams) (CreateProductColorRow, error) {
	row := q.db.QueryRowContext(ctx, createProductColor, arg.ProductID, arg.ColorName)
	var i CreateProductColorRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ColorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductColor = `-- name: DeleteProductColor :exec
DELETE FROM product_colors
WHERE id = $1
`

func (q *Queries) DeleteProductColor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductColor, id)
	return err
}

const getAllColors = `-- name: GetAllColors :many
SELECT DISTINCT c.id, c.color_name, c.color_value
FROM colors c
ORDER BY c.color_name
`

type GetAllColorsRow struct {
	ID         uuid.UUID
	ColorName  string
	ColorValue sql.NullString
}

func (q *Queries) GetAllColors(ctx context.Context) ([]GetAllColorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllColors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllColorsRow
	for rows.Next() {
		var i GetAllColorsRow
		if err := rows.Scan(&i.ID, &i.ColorName, &i.ColorValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableColorsByParentCategoryID = `-- name: GetAvailableColorsByParentCategoryID :many
WITH RECURSIVE category_tree AS (
    SELECT c.id
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
)
SELECT DISTINCT c.color_name, c.color_value
FROM products p
JOIN product_colors pc ON p.id = pc.product_id
JOIN colors c ON pc.color_id = c.id
JOIN category_tree ct ON p.category_id = ct.id
ORDER BY c.color_name
`

type GetAvailableColorsByParentCategoryIDRow struct {
	ColorName  string
	ColorValue sql.NullString
}

func (q *Queries) GetAvailableColorsByParentCategoryID(ctx context.Context, id uuid.UUID) ([]GetAvailableColorsByParentCategoryIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableColorsByParentCategoryID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailableColorsByParentCategoryIDRow
	for rows.Next() {
		var i GetAvailableColorsByParentCategoryIDRow
		if err := rows.Scan(&i.ColorName, &i.ColorValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductColorByID = `-- name: GetProductColorByID :one
SELECT pc.id, pc.product_id, c.color_name, c.color_value, pc.created_at, pc.updated_at
FROM product_colors pc
JOIN colors c ON pc.color_id = c.id
WHERE pc.id = $1
`

type GetProductColorByIDRow struct {
	ID         uuid.UUID
	ProductID  uuid.NullUUID
	ColorName  string
	ColorValue sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

func (q *Queries) GetProductColorByID(ctx context.Context, id uuid.UUID) (GetProductColorByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductColorByID, id)
	var i GetProductColorByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ColorName,
		&i.ColorValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductColorsByProductID = `-- name: ListProductColorsByProductID :many
SELECT pc.id, pc.product_id, c.color_name, c.color_value, pc.created_at, pc.updated_at
FROM product_colors pc
JOIN colors c ON pc.color_id = c.id
WHERE pc.product_id = $1
ORDER BY pc.created_at
`

type ListProductColorsByProductIDRow struct {
	ID         uuid.UUID
	ProductID  uuid.NullUUID
	ColorName  string
	ColorValue sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

func (q *Queries) ListProductColorsByProductID(ctx context.Context, productID uuid.NullUUID) ([]ListProductColorsByProductIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductColorsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductColorsByProductIDRow
	for rows.Next() {
		var i ListProductColorsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ColorName,
			&i.ColorValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductColor = `-- name: UpdateProductColor :one
UPDATE product_colors
SET color_id = (SELECT colors.id FROM colors WHERE color_name = $2), updated_at = NOW()
WHERE product_colors.id = $1
RETURNING id, product_id, color_id, created_at, updated_at
`

type UpdateProductColorParams struct {
	ID        uuid.UUID
	ColorName string
}

type UpdateProductColorRow struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	ColorID   uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateProductColor(ctx context.Context, arg UpdateProductColorParams) (UpdateProductColorRow, error) {
	row := q.db.QueryRowContext(ctx, updateProductColor, arg.ID, arg.ColorName)
	var i UpdateProductColorRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ColorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
