// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: product_sizes.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProductSize = `-- name: CreateProductSize :one
INSERT INTO product_sizes (product_id, size_id, additional_price)
VALUES ($1, (SELECT id FROM sizes WHERE size = $2), $3)
RETURNING id, product_id, size_id, additional_price, created_at, updated_at
`

type CreateProductSizeParams struct {
	ProductID       uuid.NullUUID
	Size            string
	AdditionalPrice sql.NullString
}

type CreateProductSizeRow struct {
	ID              uuid.UUID
	ProductID       uuid.NullUUID
	SizeID          uuid.NullUUID
	AdditionalPrice sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

func (q *Queries) CreateProductSize(ctx context.Context, arg CreateProductSizeParams) (CreateProductSizeRow, error) {
	row := q.db.QueryRowContext(ctx, createProductSize, arg.ProductID, arg.Size, arg.AdditionalPrice)
	var i CreateProductSizeRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SizeID,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductSize = `-- name: DeleteProductSize :exec
DELETE FROM product_sizes
WHERE id = $1
`

func (q *Queries) DeleteProductSize(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductSize, id)
	return err
}

const getAllSizes = `-- name: GetAllSizes :many
SELECT DISTINCT s.id, s.size
FROM sizes s
ORDER BY s.size
`

type GetAllSizesRow struct {
	ID   uuid.UUID
	Size string
}

func (q *Queries) GetAllSizes(ctx context.Context) ([]GetAllSizesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSizesRow
	for rows.Next() {
		var i GetAllSizesRow
		if err := rows.Scan(&i.ID, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableSizesByParentCategoryID = `-- name: GetAvailableSizesByParentCategoryID :many
WITH RECURSIVE category_tree AS (
    SELECT c.id
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT c.id
    FROM categories c
             INNER JOIN category_tree ct ON ct.id = c.parent_id
)
SELECT DISTINCT s.size
FROM products p
JOIN product_sizes ps ON p.id = ps.product_id
JOIN sizes s ON ps.size_id = s.id
JOIN category_tree ct ON p.category_id = ct.id
ORDER BY s.size
`

func (q *Queries) GetAvailableSizesByParentCategoryID(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableSizesByParentCategoryID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var size string
		if err := rows.Scan(&size); err != nil {
			return nil, err
		}
		items = append(items, size)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductSizeByID = `-- name: GetProductSizeByID :one
SELECT ps.id, ps.product_id, s.size, ps.additional_price, ps.created_at, ps.updated_at
FROM product_sizes ps
JOIN sizes s ON ps.size_id = s.id
WHERE ps.id = $1
`

type GetProductSizeByIDRow struct {
	ID              uuid.UUID
	ProductID       uuid.NullUUID
	Size            string
	AdditionalPrice sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

func (q *Queries) GetProductSizeByID(ctx context.Context, id uuid.UUID) (GetProductSizeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductSizeByID, id)
	var i GetProductSizeByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductSizesByProductID = `-- name: ListProductSizesByProductID :many
SELECT ps.id, ps.product_id, s.size, ps.additional_price, ps.created_at, ps.updated_at
FROM product_sizes ps
JOIN sizes s ON ps.size_id = s.id
WHERE ps.product_id = $1
ORDER BY ps.created_at
`

type ListProductSizesByProductIDRow struct {
	ID              uuid.UUID
	ProductID       uuid.NullUUID
	Size            string
	AdditionalPrice sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

func (q *Queries) ListProductSizesByProductID(ctx context.Context, productID uuid.NullUUID) ([]ListProductSizesByProductIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductSizesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductSizesByProductIDRow
	for rows.Next() {
		var i ListProductSizesByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Size,
			&i.AdditionalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductSize = `-- name: UpdateProductSize :one
UPDATE product_sizes
SET size_id = (SELECT sizes.id FROM sizes WHERE size = $2), additional_price = $3, updated_at = NOW()
WHERE product_sizes.id = $1
RETURNING id, product_id, size_id, additional_price, created_at, updated_at
`

type UpdateProductSizeParams struct {
	ID              uuid.UUID
	Size            string
	AdditionalPrice sql.NullString
}

type UpdateProductSizeRow struct {
	ID              uuid.UUID
	ProductID       uuid.NullUUID
	SizeID          uuid.NullUUID
	AdditionalPrice sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

func (q *Queries) UpdateProductSize(ctx context.Context, arg UpdateProductSizeParams) (UpdateProductSizeRow, error) {
	row := q.db.QueryRowContext(ctx, updateProductSize, arg.ID, arg.Size, arg.AdditionalPrice)
	var i UpdateProductSizeRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SizeID,
		&i.AdditionalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
