// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: product_analytics.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getBestSellerProducts = `-- name: GetBestSellerProducts :many
SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.stock,
    p.category_id,
    p.created_at,
    p.updated_at,
    p.status,
    p.featured,
    p.slug,
    SUM(oi.quantity) AS total_sold
FROM
    products p
        JOIN
    order_items oi ON p.id = oi.product_id
GROUP BY
    p.id
ORDER BY
    total_sold DESC
LIMIT $1
`

type GetBestSellerProductsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       sql.NullInt32
	CategoryID  uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Status      string
	Featured    sql.NullBool
	Slug        sql.NullString
	TotalSold   int64
}

func (q *Queries) GetBestSellerProducts(ctx context.Context, limit int32) ([]GetBestSellerProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBestSellerProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBestSellerProductsRow
	for rows.Next() {
		var i GetBestSellerProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Featured,
			&i.Slug,
			&i.TotalSold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyDeals = `-- name: GetDailyDeals :many
WITH first_images AS (
    SELECT DISTINCT ON (product_id) product_id, image_url
    FROM product_images
    ORDER BY product_id, created_at
)
SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.stock,
    p.category_id,
    p.created_at,
    p.updated_at,
    p.status,
    p.created_by,
    p.updated_by,
    p.featured,
    p.slug,
    d.discount_percentage,
    d.start_date,
    d.end_date,
    fi.image_url
FROM
    products p
        JOIN discounts d ON p.id = d.product_id
        LEFT JOIN first_images fi ON p.id = fi.product_id
WHERE
    p.status = true
  AND d.start_date <= now()
  AND d.end_date >= now()
ORDER BY
    d.discount_percentage DESC,
    p.created_at DESC
`

type GetDailyDealsRow struct {
	ID                 uuid.UUID
	Name               string
	Description        sql.NullString
	Price              string
	Stock              sql.NullInt32
	CategoryID         uuid.UUID
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	Status             string
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
	Featured           sql.NullBool
	Slug               sql.NullString
	DiscountPercentage string
	StartDate          sql.NullTime
	EndDate            sql.NullTime
	ImageUrl           sql.NullString
}

func (q *Queries) GetDailyDeals(ctx context.Context) ([]GetDailyDealsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyDeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyDealsRow
	for rows.Next() {
		var i GetDailyDealsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Featured,
			&i.Slug,
			&i.DiscountPercentage,
			&i.StartDate,
			&i.EndDate,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturedProducts = `-- name: GetFeaturedProducts :many
SELECT
    id,
    name,
    description,
    price,
    stock,
    category_id,
    created_at,
    updated_at,
    status,
    featured,
    slug
FROM
    products
WHERE
    featured = true
ORDER BY
    created_at DESC
LIMIT $1
`

type GetFeaturedProductsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       sql.NullInt32
	CategoryID  uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Status      string
	Featured    sql.NullBool
	Slug        sql.NullString
}

func (q *Queries) GetFeaturedProducts(ctx context.Context, limit int32) ([]GetFeaturedProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeaturedProductsRow
	for rows.Next() {
		var i GetFeaturedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Featured,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewArrivalProducts = `-- name: GetNewArrivalProducts :many
SELECT
    id,
    name,
    description,
    price,
    stock,
    category_id,
    created_at,
    updated_at,
    status,
    featured,
    slug
FROM
    products
WHERE
    status = true
  AND created_at >= NOW() - INTERVAL '100 days'
ORDER BY
    created_at DESC
LIMIT $1
`

type GetNewArrivalProductsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       sql.NullInt32
	CategoryID  uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Status      string
	Featured    sql.NullBool
	Slug        sql.NullString
}

func (q *Queries) GetNewArrivalProducts(ctx context.Context, limit int32) ([]GetNewArrivalProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNewArrivalProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewArrivalProductsRow
	for rows.Next() {
		var i GetNewArrivalProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Featured,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
