// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: products_sepcifications.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProductSpecification = `-- name: CreateProductSpecification :one
INSERT INTO product_specifications (product_id, spec_name, spec_value)
VALUES ($1, $2, $3)
    RETURNING id, product_id, spec_name, spec_value, created_at, updated_at
`

type CreateProductSpecificationParams struct {
	ProductID uuid.NullUUID
	SpecName  string
	SpecValue string
}

func (q *Queries) CreateProductSpecification(ctx context.Context, arg CreateProductSpecificationParams) (ProductSpecification, error) {
	row := q.db.QueryRowContext(ctx, createProductSpecification, arg.ProductID, arg.SpecName, arg.SpecValue)
	var i ProductSpecification
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SpecName,
		&i.SpecValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductSpecification = `-- name: DeleteProductSpecification :exec
DELETE FROM product_specifications
WHERE id = $1
`

func (q *Queries) DeleteProductSpecification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductSpecification, id)
	return err
}

const getProductSpecificationByID = `-- name: GetProductSpecificationByID :one
SELECT id, product_id, spec_name, spec_value, created_at, updated_at
FROM product_specifications
WHERE id = $1
`

func (q *Queries) GetProductSpecificationByID(ctx context.Context, id uuid.UUID) (ProductSpecification, error) {
	row := q.db.QueryRowContext(ctx, getProductSpecificationByID, id)
	var i ProductSpecification
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SpecName,
		&i.SpecValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductSpecificationsByProductID = `-- name: ListProductSpecificationsByProductID :many
SELECT id, product_id, spec_name, spec_value, created_at, updated_at
FROM product_specifications
WHERE product_id = $1
ORDER BY spec_name
`

func (q *Queries) ListProductSpecificationsByProductID(ctx context.Context, productID uuid.NullUUID) ([]ProductSpecification, error) {
	rows, err := q.db.QueryContext(ctx, listProductSpecificationsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductSpecification
	for rows.Next() {
		var i ProductSpecification
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SpecName,
			&i.SpecValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductSpecification = `-- name: UpdateProductSpecification :one
UPDATE product_specifications
SET spec_name = $2, spec_value = $3, updated_at = NOW()
WHERE id = $1
    RETURNING id, product_id, spec_name, spec_value, created_at, updated_at
`

type UpdateProductSpecificationParams struct {
	ID        uuid.UUID
	SpecName  string
	SpecValue string
}

func (q *Queries) UpdateProductSpecification(ctx context.Context, arg UpdateProductSpecificationParams) (ProductSpecification, error) {
	row := q.db.QueryRowContext(ctx, updateProductSpecification, arg.ID, arg.SpecName, arg.SpecValue)
	var i ProductSpecification
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SpecName,
		&i.SpecValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
