// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: promotions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addProductToPromotion = `-- name: AddProductToPromotion :exec
INSERT INTO promotion_products (promotion_id, product_id)
VALUES ($1, $2)
`

type AddProductToPromotionParams struct {
	PromotionID uuid.UUID
	ProductID   uuid.UUID
}

func (q *Queries) AddProductToPromotion(ctx context.Context, arg AddProductToPromotionParams) error {
	_, err := q.db.ExecContext(ctx, addProductToPromotion, arg.PromotionID, arg.ProductID)
	return err
}

const createPromotion = `-- name: CreatePromotion :one
INSERT INTO promotions (tagline, main_title, subtitle, title, description, image_url, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tagline, main_title, subtitle, title, description, image_url, start_date, end_date, created_at, updated_at
`

type CreatePromotionParams struct {
	Tagline     sql.NullString
	MainTitle   string
	Subtitle    string
	Title       string
	Description sql.NullString
	ImageUrl    sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
}

type CreatePromotionRow struct {
	ID          uuid.UUID
	Tagline     sql.NullString
	MainTitle   string
	Subtitle    string
	Title       string
	Description sql.NullString
	ImageUrl    sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (CreatePromotionRow, error) {
	row := q.db.QueryRowContext(ctx, createPromotion,
		arg.Tagline,
		arg.MainTitle,
		arg.Subtitle,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.StartDate,
		arg.EndDate,
	)
	var i CreatePromotionRow
	err := row.Scan(
		&i.ID,
		&i.Tagline,
		&i.MainTitle,
		&i.Subtitle,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromotionsWithProducts = `-- name: GetPromotionsWithProducts :many
WITH first_images AS (
    SELECT DISTINCT ON (product_id)
        product_id,
        image_url
    FROM
        product_images
    ORDER BY
        product_id,
        created_at
),
     active_discounts AS (
         SELECT
             product_id,
             discount_percentage
         FROM
             discounts
         WHERE
             start_date <= NOW() AND end_date >= NOW()
     )
SELECT
    p.id AS promotion_id,
    p.tagline,
    p.main_title,
    p.subtitle,
    p.title,
    p.description,
    p.image_url AS promotion_image_url,
    p.start_date,
    p.end_date,
    p.created_at,
    p.updated_at,
    pr.id AS product_id,
    pr.name AS product_name,
    pr.description AS product_description,
    pr.price,
    COALESCE(ad.discount_percentage, 0) AS discount_percentage,
    fi.image_url AS product_image_url
FROM
    promotions p
        JOIN promotion_products pp ON p.id = pp.promotion_id
        JOIN products pr ON pp.product_id = pr.id
        LEFT JOIN first_images fi ON pr.id = fi.product_id
        LEFT JOIN active_discounts ad ON pr.id = ad.product_id
ORDER BY
    p.created_at DESC
`

type GetPromotionsWithProductsRow struct {
	PromotionID        uuid.UUID
	Tagline            sql.NullString
	MainTitle          string
	Subtitle           string
	Title              string
	Description        sql.NullString
	PromotionImageUrl  sql.NullString
	StartDate          sql.NullTime
	EndDate            sql.NullTime
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	ProductID          uuid.UUID
	ProductName        string
	ProductDescription sql.NullString
	Price              string
	DiscountPercentage string
	ProductImageUrl    sql.NullString
}

func (q *Queries) GetPromotionsWithProducts(ctx context.Context) ([]GetPromotionsWithProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPromotionsWithProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPromotionsWithProductsRow
	for rows.Next() {
		var i GetPromotionsWithProductsRow
		if err := rows.Scan(
			&i.PromotionID,
			&i.Tagline,
			&i.MainTitle,
			&i.Subtitle,
			&i.Title,
			&i.Description,
			&i.PromotionImageUrl,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductID,
			&i.ProductName,
			&i.ProductDescription,
			&i.Price,
			&i.DiscountPercentage,
			&i.ProductImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
