// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: promotions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addProductToPromotion = `-- name: AddProductToPromotion :exec
INSERT INTO promotion_products (promotion_id, product_id)
VALUES ($1, $2)
`

type AddProductToPromotionParams struct {
	PromotionID uuid.UUID
	ProductID   uuid.UUID
}

func (q *Queries) AddProductToPromotion(ctx context.Context, arg AddProductToPromotionParams) error {
	_, err := q.db.ExecContext(ctx, addProductToPromotion, arg.PromotionID, arg.ProductID)
	return err
}

const createPromotion = `-- name: CreatePromotion :one
INSERT INTO promotions (title, description, image_url)
VALUES ($1, $2, $3)
RETURNING id, title, description, image_url, created_at, updated_at
`

type CreatePromotionParams struct {
	Title       string
	Description sql.NullString
	ImageUrl    sql.NullString
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (Promotion, error) {
	row := q.db.QueryRowContext(ctx, createPromotion, arg.Title, arg.Description, arg.ImageUrl)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
