// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateProductsBySlugs(ctx context.Context, arg ActivateProductsBySlugsParams) error
	ActivatePromotions(ctx context.Context, dollar_1 []string) error
	AddProductToPromotion(ctx context.Context, arg AddProductToPromotionParams) error
	AddProductsToPromotion(ctx context.Context, arg AddProductsToPromotionParams) error
	ApproveAdminRequest(ctx context.Context, id uuid.UUID) error
	ArchiveProductByID(ctx context.Context, id uuid.UUID) error
	ArchiveProductsBySlugs(ctx context.Context, arg ArchiveProductsBySlugsParams) error
	ArchivePromotions(ctx context.Context, dollar_1 []string) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (AssignRoleToUserRow, error)
	// Calculate the total price of items in the cart
	CalculateCartTotal(ctx context.Context, shoppingCartID uuid.UUID) (string, error)
	CancelOrder(ctx context.Context, id uuid.UUID) (sql.NullString, error)
	ChangeOrderPaymentMethod(ctx context.Context, arg ChangeOrderPaymentMethodParams) (sql.NullString, error)
	CheckCategoryExistence(ctx context.Context, id uuid.UUID) (bool, error)
	// Remove all items from the cart
	ClearCart(ctx context.Context, shoppingCartID uuid.UUID) error
	CountAllProductsByFilters(ctx context.Context, arg CountAllProductsByFiltersParams) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountProductsByParentCategoryID(ctx context.Context, id uuid.UUID) (int64, error)
	CreateAdminRequest(ctx context.Context, arg CreateAdminRequestParams) (uuid.UUID, error)
	// Create a shopping cart for a guest
	CreateCartForGuest(ctx context.Context, guestID uuid.NullUUID) (ShoppingCart, error)
	// Create a shopping cart for a user
	CreateCartForUser(ctx context.Context, userID uuid.NullUUID) (ShoppingCart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (uuid.UUID, error)
	CreateDiscount(ctx context.Context, arg CreateDiscountParams) (Discount, error)
	CreateGuestCheckout(ctx context.Context, arg CreateGuestCheckoutParams) (uuid.UUID, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (uuid.UUID, error)
	CreateOrderItemOption(ctx context.Context, arg CreateOrderItemOptionParams) error
	CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (uuid.UUID, error)
	CreateProductAttributeValue(ctx context.Context, arg CreateProductAttributeValueParams) (uuid.UUID, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (ProductOption, error)
	CreateProductOptionValue(ctx context.Context, arg CreateProductOptionValueParams) (ProductOptionValue, error)
	CreateProductSpecification(ctx context.Context, arg CreateProductSpecificationParams) (ProductSpecification, error)
	CreateProductToAttributeValue(ctx context.Context, arg CreateProductToAttributeValueParams) error
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreatePromotion(ctx context.Context, arg CreatePromotionParams) (CreatePromotionRow, error)
	CreateRelatedProduct(ctx context.Context, arg CreateRelatedProductParams) (RelatedProduct, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShoppingCart(ctx context.Context, arg CreateShoppingCartParams) (ShoppingCart, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) (DeactivateUserRow, error)
	DeleteApprovalToken(ctx context.Context, token string) error
	DeleteDiscount(ctx context.Context, id uuid.UUID) error
	DeleteExchangeRate(ctx context.Context, arg DeleteExchangeRateParams) error
	DeleteExpiredTResets(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	DeletePasswordResetToken(ctx context.Context, email string) error
	DeleteProductByID(ctx context.Context, id uuid.UUID) error
	DeleteProductImage(ctx context.Context, id uuid.UUID) error
	DeleteProductImagesByProductID(ctx context.Context, productID uuid.NullUUID) error
	DeleteProductOption(ctx context.Context, id uuid.UUID) error
	DeleteProductOptionValue(ctx context.Context, id uuid.UUID) error
	DeleteProductSpecification(ctx context.Context, id uuid.UUID) error
	DeleteProductSpecificationsByProductID(ctx context.Context, productID uuid.NullUUID) error
	DeleteProductVariant(ctx context.Context, id uuid.UUID) error
	DeleteProductsBySlugs(ctx context.Context, dollar_1 []string) error
	DeletePromotion(ctx context.Context, slug string) error
	DeletePromotions(ctx context.Context, dollar_1 []string) error
	DeleteRelatedProduct(ctx context.Context, arg DeleteRelatedProductParams) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	DeleteSessionBySessionID(ctx context.Context, sessionID uuid.UUID) error
	// Delete a shopping cart
	DeleteShoppingCart(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteVerificationTokenByToken(ctx context.Context, token string) error
	DeleteVerificationTokensByEmail(ctx context.Context, email string) error
	DraftProductsBySlugs(ctx context.Context, arg DraftProductsBySlugsParams) error
	DraftPromotions(ctx context.Context, dollar_1 []string) error
	GetActiveDiscountsByProductIDs(ctx context.Context, arg GetActiveDiscountsByProductIDsParams) ([]GetActiveDiscountsByProductIDsRow, error)
	GetAdminRequestByID(ctx context.Context, id uuid.UUID) (GetAdminRequestByIDRow, error)
	GetAdminRequestByUserID(ctx context.Context, userID uuid.UUID) (AdminRequest, error)
	GetAdminRequestsByUserID(ctx context.Context, userID uuid.UUID) ([]GetAdminRequestsByUserIDRow, error)
	// Get all items in the cart
	GetAllCartItems(ctx context.Context, shoppingCartID uuid.UUID) ([]GetAllCartItemsRow, error)
	GetAllExchangeRatesForCurrency(ctx context.Context, currencyCode string) ([]ExchangeRate, error)
	GetAllPayments(ctx context.Context) ([]GetAllPaymentsRow, error)
	GetAllProductsByFiltersNameAsc(ctx context.Context, arg GetAllProductsByFiltersNameAscParams) ([]GetAllProductsByFiltersNameAscRow, error)
	GetAllProductsByFiltersNameDesc(ctx context.Context, arg GetAllProductsByFiltersNameDescParams) ([]GetAllProductsByFiltersNameDescRow, error)
	GetAllProductsByFiltersNewest(ctx context.Context, arg GetAllProductsByFiltersNewestParams) ([]GetAllProductsByFiltersNewestRow, error)
	GetAllProductsByFiltersOldest(ctx context.Context, arg GetAllProductsByFiltersOldestParams) ([]GetAllProductsByFiltersOldestRow, error)
	GetAllProductsByFiltersPriceAsc(ctx context.Context, arg GetAllProductsByFiltersPriceAscParams) ([]GetAllProductsByFiltersPriceAscRow, error)
	GetAllProductsByFiltersPriceDesc(ctx context.Context, arg GetAllProductsByFiltersPriceDescParams) ([]GetAllProductsByFiltersPriceDescRow, error)
	GetAllRoles(ctx context.Context) ([]Role, error)
	GetApprovalToken(ctx context.Context, token string) (AdminApprovalToken, error)
	GetBestSellerProducts(ctx context.Context, limit int32) ([]GetBestSellerProductsRow, error)
	// Get a shopping cart by guest ID
	GetCartByGuestID(ctx context.Context, guestID uuid.NullUUID) (ShoppingCart, error)
	// cart_queries.sql
	// Get a cart item
	GetCartItem(ctx context.Context, arg GetCartItemParams) (GetCartItemRow, error)
	GetCategoriesByParentID(ctx context.Context, parentID uuid.NullUUID) ([]GetCategoriesByParentIDRow, error)
	GetCategoriesWithProductsCount(ctx context.Context) ([]GetCategoriesWithProductsCountRow, error)
	GetCategoriesWithSubcategoryCount(ctx context.Context) ([]GetCategoriesWithSubcategoryCountRow, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (GetCategoryByIDRow, error)
	GetCategoryByName(ctx context.Context, name string) (GetCategoryByNameRow, error)
	GetCategoryBySlug(ctx context.Context, slug string) (uuid.UUID, error)
	GetCategoryDetailsBySlug(ctx context.Context, slug string) (GetCategoryDetailsBySlugRow, error)
	// $1: category_id (UUID)
	// $2: min_price_kes (NUMERIC)
	// $3: max_price_kes (NUMERIC)
	// $4: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
	// $5: limit (INTEGER)
	// $6: offset (INTEGER)
	GetCategoryProductsByFiltersNameAsc(ctx context.Context, arg GetCategoryProductsByFiltersNameAscParams) ([]GetCategoryProductsByFiltersNameAscRow, error)
	// $1: category_id (UUID)
	// $2: min_price_kes (NUMERIC)
	// $3: max_price_kes (NUMERIC)
	// $4: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
	// $5: limit (INTEGER)
	// $6: offset (INTEGER)
	GetCategoryProductsByFiltersNameDesc(ctx context.Context, arg GetCategoryProductsByFiltersNameDescParams) ([]GetCategoryProductsByFiltersNameDescRow, error)
	GetCategoryProductsByFiltersNewest(ctx context.Context, arg GetCategoryProductsByFiltersNewestParams) ([]GetCategoryProductsByFiltersNewestRow, error)
	// $1: category_id (UUID)
	// $2: min_price_kes (NUMERIC)
	// $3: max_price_kes (NUMERIC)
	// $4: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
	// $5: limit (INTEGER)
	// $6: offset (INTEGER)
	GetCategoryProductsByFiltersOldest(ctx context.Context, arg GetCategoryProductsByFiltersOldestParams) ([]GetCategoryProductsByFiltersOldestRow, error)
	// $1: category_id (UUID)
	// $2: min_price_kes (NUMERIC)
	// $3: max_price_kes (NUMERIC)
	// $4: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
	// $5: limit (INTEGER)
	// $6: offset (INTEGER)
	GetCategoryProductsByFiltersPriceAsc(ctx context.Context, arg GetCategoryProductsByFiltersPriceAscParams) ([]GetCategoryProductsByFiltersPriceAscRow, error)
	// $1: category_id (UUID)
	// $2: min_price_kes (NUMERIC)
	// $3: max_price_kes (NUMERIC)
	// $4: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
	// $5: limit (INTEGER)
	// $6: offset (INTEGER)
	GetCategoryProductsByFiltersPriceDesc(ctx context.Context, arg GetCategoryProductsByFiltersPriceDescParams) ([]GetCategoryProductsByFiltersPriceDescRow, error)
	GetCategorySEOBySlug(ctx context.Context, slug string) (GetCategorySEOBySlugRow, error)
	GetCategoryTree(ctx context.Context) ([]GetCategoryTreeRow, error)
	GetCompany(ctx context.Context, arg GetCompanyParams) (uuid.UUID, error)
	GetDailyDeals(ctx context.Context) ([]GetDailyDealsRow, error)
	GetDiscountByID(ctx context.Context, id uuid.UUID) (Discount, error)
	GetDiscountByProductID(ctx context.Context, productID uuid.NullUUID) (Discount, error)
	GetFeaturedProducts(ctx context.Context, limit int32) ([]GetFeaturedProductsRow, error)
	GetGuestCheckoutByEmail(ctx context.Context, email string) (GuestCheckout, error)
	GetImageKeysByProductID(ctx context.Context, productID uuid.NullUUID) ([]string, error)
	GetLatestExchangeRate(ctx context.Context, currencyCode string) (string, error)
	GetMonthlyRevenue(ctx context.Context, paymentStatusID sql.NullInt32) ([]GetMonthlyRevenueRow, error)
	// GetMonthlySales retrieves the total sales for each month from the order_payments table
	GetMonthlySales(ctx context.Context, paymentStatusID sql.NullInt32) ([]GetMonthlySalesRow, error)
	GetMonthlySalesForLastTwoMonths(ctx context.Context, paymentStatusID sql.NullInt32) (GetMonthlySalesForLastTwoMonthsRow, error)
	GetNewArrivalProducts(ctx context.Context, limit int32) ([]GetNewArrivalProductsRow, error)
	GetOrderById(ctx context.Context, id uuid.UUID) (GetOrderByIdRow, error)
	GetOrderIDsByUserID(ctx context.Context, userID uuid.NullUUID) ([]uuid.UUID, error)
	GetOrderItemsByOrderId(ctx context.Context, orderID uuid.NullUUID) ([]GetOrderItemsByOrderIdRow, error)
	GetOrdersByGuestCheckoutId(ctx context.Context, guestCheckoutID uuid.NullUUID) ([]GetOrdersByGuestCheckoutIdRow, error)
	GetOrdersByUserId(ctx context.Context, userID uuid.NullUUID) ([]GetOrdersByUserIdRow, error)
	GetParentCategories(ctx context.Context) ([]GetParentCategoriesRow, error)
	GetPasswordResetToken(ctx context.Context, email string) (PasswordResetToken, error)
	GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (GetPaymentByOrderIDRow, error)
	GetPaymentStatusIDByStatus(ctx context.Context, status string) (int32, error)
	GetPendingAdminRequests(ctx context.Context) ([]GetPendingAdminRequestsRow, error)
	GetProductAttributes(ctx context.Context) (GetProductAttributesRow, error)
	GetProductAttributesByCategoryID(ctx context.Context, id uuid.UUID) (GetProductAttributesByCategoryIDRow, error)
	GetProductAttributesByCategoryName(ctx context.Context, name string) (GetProductAttributesByCategoryNameRow, error)
	GetProductAttributesWithValues(ctx context.Context, categoryID uuid.NullUUID) ([]GetProductAttributesWithValuesRow, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetProductByIDsRow, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetProductCartByProductSlug(ctx context.Context, slug string) (GetProductCartByProductSlugRow, error)
	GetProductIDsByPromotionID(ctx context.Context, promotionID uuid.UUID) ([]uuid.UUID, error)
	GetProductIDsBySlugs(ctx context.Context, dollar_1 []string) ([]uuid.UUID, error)
	GetProductImageByID(ctx context.Context, id uuid.UUID) (ProductImage, error)
	GetProductOptionByID(ctx context.Context, id uuid.UUID) (ProductOption, error)
	GetProductOptionValueByID(ctx context.Context, id uuid.UUID) (ProductOptionValue, error)
	GetProductPricingByProductID(ctx context.Context, id uuid.UUID) (GetProductPricingByProductIDRow, error)
	GetProductSEO(ctx context.Context, slug string) (GetProductSEORow, error)
	GetProductSlugByProductID(ctx context.Context, id uuid.UUID) (string, error)
	GetProductSpecificationByID(ctx context.Context, id uuid.UUID) (ProductSpecification, error)
	GetProductSpecsByID(ctx context.Context, id uuid.UUID) (GetProductSpecsByIDRow, error)
	GetProductVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error)
	GetProductsByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]GetProductsByCategoryIDRow, error)
	GetProductsByParentCategoryID(ctx context.Context, arg GetProductsByParentCategoryIDParams) ([]GetProductsByParentCategoryIDRow, error)
	GetPromotionBySlug(ctx context.Context, slug string) (Promotion, error)
	// This function will fetch the promotion details along with associated products.
	GetPromotionDetails(ctx context.Context, slug string) ([]GetPromotionDetailsRow, error)
	GetPromotions(ctx context.Context) ([]GetPromotionsRow, error)
	GetRecentSales(ctx context.Context) ([]GetRecentSalesRow, error)
	GetRelatedProductByProductID(ctx context.Context, productID uuid.UUID) (RelatedProduct, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleByName(ctx context.Context, roleName string) (GetRoleByNameRow, error)
	GetSalesTrend(ctx context.Context, paymentStatusID sql.NullInt32) (GetSalesTrendRow, error)
	GetSessionBySessionID(ctx context.Context, sessionID uuid.UUID) (Session, error)
	GetSessionByUserID(ctx context.Context, userID uuid.NullUUID) ([]Session, error)
	// Get a shopping cart by ID
	GetShoppingCartByID(ctx context.Context, id uuid.UUID) (ShoppingCart, error)
	// Get a shopping cart by user ID
	GetShoppingCartByUserID(ctx context.Context, userID uuid.NullUUID) (ShoppingCart, error)
	GetStatusByID(ctx context.Context, id int32) (string, error)
	// $1: category_id (UUID)
	// $2: min_price_kes (NUMERIC)
	// $3: max_price_kes (NUMERIC)
	// $4: selected_attributes (JSONB) -- {"size": ["14-inch", "15-inch"], "color": ["red", "blue"]}
	GetTotalCategoryProductsByFilters(ctx context.Context, arg GetTotalCategoryProductsByFiltersParams) (int64, error)
	// GetTotalRevenueByStatus gets the total revenue for orders with a specific payment status
	GetTotalRevenueByPaymentStatus(ctx context.Context, paymentStatusID sql.NullInt32) (string, error)
	GetTotalRevenueForLastTwoMonths(ctx context.Context, paymentStatusID sql.NullInt32) (GetTotalRevenueForLastTwoMonthsRow, error)
	GetTotalSalesCurrentMonth(ctx context.Context) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (GetUserByProviderRow, error)
	GetUserOrGuestCheckoutNameByOrderID(ctx context.Context, id uuid.UUID) (GetUserOrGuestCheckoutNameByOrderIDRow, error)
	GetUserProfileByID(ctx context.Context, id uuid.UUID) (GetUserProfileByIDRow, error)
	GetUserRecommendations(ctx context.Context, arg GetUserRecommendationsParams) ([]GetUserRecommendationsRow, error)
	GetUserRoles(ctx context.Context, userID uuid.NullUUID) ([]GetUserRolesRow, error)
	GetUserRolesByUserID(ctx context.Context, userID uuid.NullUUID) ([]string, error)
	GetUsersByRole(ctx context.Context, roleID uuid.NullUUID) ([]GetUsersByRoleRow, error)
	GetV2CategoryHierarchy(ctx context.Context) ([]GetV2CategoryHierarchyRow, error)
	GetV2ProductDetailBySlug(ctx context.Context, slug string) (GetV2ProductDetailBySlugRow, error)
	GetV2Products(ctx context.Context) ([]GetV2ProductsRow, error)
	GetV2Promotions(ctx context.Context) ([]GetV2PromotionsRow, error)
	GetVATPercentage(ctx context.Context) (string, error)
	GetVerificationTokenByEmail(ctx context.Context, email string) (VerificationToken, error)
	GetVerificationTokenByToken(ctx context.Context, token string) (VerificationToken, error)
	HardDeleteCategory(ctx context.Context, id uuid.UUID) error
	InsertExchangeRate(ctx context.Context, arg InsertExchangeRateParams) error
	IsAdmin(ctx context.Context, userID uuid.NullUUID) (bool, error)
	LinkSessionToUser(ctx context.Context, arg LinkSessionToUserParams) error
	ListCategories(ctx context.Context) ([]ListCategoriesRow, error)
	ListDiscounts(ctx context.Context) ([]Discount, error)
	ListDiscountsByProductID(ctx context.Context, productID uuid.NullUUID) ([]Discount, error)
	ListProductImagesByProductID(ctx context.Context, productID uuid.NullUUID) ([]ProductImage, error)
	ListProductOptionValuesByOptionID(ctx context.Context, optionID uuid.NullUUID) ([]ProductOptionValue, error)
	ListProductOptionsByProductID(ctx context.Context, productID uuid.NullUUID) ([]ProductOption, error)
	ListProductSpecificationsByProductID(ctx context.Context, productID uuid.NullUUID) ([]ProductSpecification, error)
	ListProductVariantsByProductID(ctx context.Context, productID uuid.NullUUID) ([]ProductVariant, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListRelatedProductsByProductID(ctx context.Context, productID uuid.UUID) ([]RelatedProduct, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	MakeAdmin(ctx context.Context, userID uuid.NullUUID) error
	RejectAdminRequest(ctx context.Context, id uuid.UUID) error
	RemoveAllRolesFromUser(ctx context.Context, userID uuid.NullUUID) error
	// Remove an item from the cart
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	RemoveProductsFromPromotion(ctx context.Context, arg RemoveProductsFromPromotionParams) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	SearchProducts(ctx context.Context, dollar_1 sql.NullString) ([]SearchProductsRow, error)
	SoftDeleteCategory(ctx context.Context, id uuid.UUID) error
	SoftDeleteProduct(ctx context.Context, id uuid.UUID) error
	StoreApprovalToken(ctx context.Context, arg StoreApprovalTokenParams) error
	StorePasswordResetToken(ctx context.Context, arg StorePasswordResetTokenParams) error
	StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) (StoreRefreshTokenRow, error)
	// Update the cart to associate with a guest ID and nullify user_id
	UpdateCartGuestID(ctx context.Context, arg UpdateCartGuestIDParams) error
	// Update the quantity of an item in the cart
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateCartTotals(ctx context.Context, id uuid.UUID) error
	// Update the cart's user ID and nullify guest_id
	UpdateCartUserID(ctx context.Context, arg UpdateCartUserIDParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error)
	UpdateCategoryImage(ctx context.Context, arg UpdateCategoryImageParams) (UpdateCategoryImageRow, error)
	UpdateCheckoutRequestIDByOrderID(ctx context.Context, arg UpdateCheckoutRequestIDByOrderIDParams) error
	UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) (Discount, error)
	UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) error
	UpdateOrderAmounts(ctx context.Context, arg UpdateOrderAmountsParams) (UpdateOrderAmountsRow, error)
	UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (ProductImage, error)
	UpdateProductImages(ctx context.Context, arg UpdateProductImagesParams) error
	UpdateProductOption(ctx context.Context, arg UpdateProductOptionParams) (ProductOption, error)
	UpdateProductOptionValue(ctx context.Context, arg UpdateProductOptionValueParams) (ProductOptionValue, error)
	UpdateProductSEO(ctx context.Context, arg UpdateProductSEOParams) error
	UpdateProductSpecification(ctx context.Context, arg UpdateProductSpecificationParams) (ProductSpecification, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) error
	UpdatePromotionImage(ctx context.Context, arg UpdatePromotionImageParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateSessionLastActivity(ctx context.Context, sessionID uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserCompany(ctx context.Context, arg UpdateUserCompanyParams) error
	UpdateUserEmailVerified(ctx context.Context, email string) error
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) (UpdateUserLastLoginRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	UpdateVATPercentage(ctx context.Context, vatPercentage string) error
	// Insert or update the item in the cart
	UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (UpsertCartItemRow, error)
	UpsertProductSpecification(ctx context.Context, arg UpsertProductSpecificationParams) (ProductSpecification, error)
}

var _ Querier = (*Queries)(nil)
