// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: recommendations.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserRecommendations = `-- name: GetUserRecommendations :many
SELECT
    r.product_id,
    p.name,
    p.description,
    p.usd_price,
    r.score
FROM
    recommendations r
        JOIN
    products p ON r.product_id = p.id
WHERE
    r.user_id = $1
ORDER BY
    r.score DESC
    LIMIT $2
`

type GetUserRecommendationsParams struct {
	UserID uuid.NullUUID
	Limit  int32
}

type GetUserRecommendationsRow struct {
	ProductID   uuid.NullUUID
	Name        string
	Description sql.NullString
	UsdPrice    string
	Score       int64
}

func (q *Queries) GetUserRecommendations(ctx context.Context, arg GetUserRecommendationsParams) ([]GetUserRecommendationsRow, error) {
	rows, err := q.query(ctx, q.getUserRecommendationsStmt, getUserRecommendations, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRecommendationsRow{}
	for rows.Next() {
		var i GetUserRecommendationsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.UsdPrice,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
