// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: related_products.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRelatedProduct = `-- name: CreateRelatedProduct :one
INSERT INTO related_products (product_id, related_product_id)
VALUES ($1, $2)
    RETURNING product_id, related_product_id
`

type CreateRelatedProductParams struct {
	ProductID        uuid.UUID
	RelatedProductID uuid.UUID
}

func (q *Queries) CreateRelatedProduct(ctx context.Context, arg CreateRelatedProductParams) (RelatedProduct, error) {
	row := q.queryRow(ctx, q.createRelatedProductStmt, createRelatedProduct, arg.ProductID, arg.RelatedProductID)
	var i RelatedProduct
	err := row.Scan(&i.ProductID, &i.RelatedProductID)
	return i, err
}

const deleteRelatedProduct = `-- name: DeleteRelatedProduct :exec
DELETE FROM related_products
WHERE product_id = $1 AND related_product_id = $2
`

type DeleteRelatedProductParams struct {
	ProductID        uuid.UUID
	RelatedProductID uuid.UUID
}

func (q *Queries) DeleteRelatedProduct(ctx context.Context, arg DeleteRelatedProductParams) error {
	_, err := q.exec(ctx, q.deleteRelatedProductStmt, deleteRelatedProduct, arg.ProductID, arg.RelatedProductID)
	return err
}

const getRelatedProductByProductID = `-- name: GetRelatedProductByProductID :one
SELECT product_id, related_product_id
FROM related_products
WHERE product_id = $1
`

func (q *Queries) GetRelatedProductByProductID(ctx context.Context, productID uuid.UUID) (RelatedProduct, error) {
	row := q.queryRow(ctx, q.getRelatedProductByProductIDStmt, getRelatedProductByProductID, productID)
	var i RelatedProduct
	err := row.Scan(&i.ProductID, &i.RelatedProductID)
	return i, err
}

const listRelatedProductsByProductID = `-- name: ListRelatedProductsByProductID :many
SELECT product_id, related_product_id
FROM related_products
WHERE product_id = $1
ORDER BY related_product_id
`

func (q *Queries) ListRelatedProductsByProductID(ctx context.Context, productID uuid.UUID) ([]RelatedProduct, error) {
	rows, err := q.query(ctx, q.listRelatedProductsByProductIDStmt, listRelatedProductsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RelatedProduct{}
	for rows.Next() {
		var i RelatedProduct
		if err := rows.Scan(&i.ProductID, &i.RelatedProductID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
