// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reset_password.sql

package database

import (
	"context"
	"time"
)

const deleteExpiredTResets = `-- name: DeleteExpiredTResets :exec
DELETE FROM password_reset_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredTResets(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredTResetsStmt, deleteExpiredTResets)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens
WHERE email = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, email string) error {
	_, err := q.exec(ctx, q.deletePasswordResetTokenStmt, deletePasswordResetToken, email)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, email, token, expires_at, created_at
FROM password_reset_tokens
WHERE email = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, email string) (PasswordResetToken, error) {
	row := q.queryRow(ctx, q.getPasswordResetTokenStmt, getPasswordResetToken, email)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const storePasswordResetToken = `-- name: StorePasswordResetToken :exec
INSERT INTO password_reset_tokens (email, token, expires_at)
VALUES ($1, $2, $3)
`

type StorePasswordResetTokenParams struct {
	Email     string
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) StorePasswordResetToken(ctx context.Context, arg StorePasswordResetTokenParams) error {
	_, err := q.exec(ctx, q.storePasswordResetTokenStmt, storePasswordResetToken, arg.Email, arg.Token, arg.ExpiresAt)
	return err
}
