// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: roles.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (role_name, description)
VALUES ($1, $2)
RETURNING id, role_name, description, created_at, updated_at
`

type CreateRoleParams struct {
	RoleName    string
	Description sql.NullString
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.RoleName, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT id, role_name, description, created_at, updated_at
FROM roles
ORDER BY role_name
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, role_name, description, created_at, updated_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, role_name
FROM roles
WHERE role_name = $1
`

type GetRoleByNameRow struct {
	ID       uuid.UUID
	RoleName string
}

func (q *Queries) GetRoleByName(ctx context.Context, roleName string) (GetRoleByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, roleName)
	var i GetRoleByNameRow
	err := row.Scan(&i.ID, &i.RoleName)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET role_name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, role_name, description, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID
	RoleName    string
	Description sql.NullString
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole, arg.ID, arg.RoleName, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
