// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: search.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const autocompleteSuggestions = `-- name: AutocompleteSuggestions :many
WITH term AS (
  SELECT lower($1) AS term
)
SELECT suggestion
FROM (
  SELECT name AS suggestion
  FROM products
  CROSS JOIN term
  WHERE lower(name) ILIKE '%' || term.term || '%'
  UNION
  SELECT name AS suggestion
  FROM categories
  CROSS JOIN term
  WHERE lower(name) ILIKE '%' || term.term || '%'
) AS sub
ORDER BY suggestion
LIMIT $2
`

type AutocompleteSuggestionsParams struct {
	Lower string
	Limit int32
}

// Returns distinct suggestions for auto-completion based on product and category names.
func (q *Queries) AutocompleteSuggestions(ctx context.Context, arg AutocompleteSuggestionsParams) ([]string, error) {
	rows, err := q.query(ctx, q.autocompleteSuggestionsStmt, autocompleteSuggestions, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var suggestion string
		if err := rows.Scan(&suggestion); err != nil {
			return nil, err
		}
		items = append(items, suggestion)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const v2SearchProducts = `-- name: V2SearchProducts :many
WITH
  search_query AS (
    SELECT to_tsquery('english', string_agg(word || ':*', ' & ')) AS query
    FROM regexp_split_to_table($1, '\s+') AS word
  ),
  search_term AS (
    SELECT lower($1) AS term
  ),
  usd_rate AS (
    SELECT rate_to_kes
    FROM exchange_rates
    WHERE currency_code = 'USD'
      AND now() BETWEEN valid_from AND COALESCE(valid_to, now() + interval '100 years')
    ORDER BY valid_from DESC
    LIMIT 1
  ),
  ft_results AS (
    SELECT
      p.id,
      p.name,
      (p.usd_price * ur.rate_to_kes) AS price_in_kes,
      p.slug,
      ts_rank_cd(p.search_keyword, sq.query) AS rank
    FROM products p
    CROSS JOIN usd_rate ur
    CROSS JOIN search_query sq
    WHERE p.status = 'active'
      AND p.search_keyword @@ sq.query
  ),
  ilike_results AS (
    SELECT DISTINCT
      p.id,
      p.name,
      (p.usd_price * ur.rate_to_kes) AS price_in_kes,
      p.slug,
      0::double precision AS rank
    FROM products p
    LEFT JOIN categories c ON p.category_id = c.id
    CROSS JOIN usd_rate ur
    CROSS JOIN search_term st
    WHERE p.status = 'active'
      AND (
        lower(p.name) ILIKE '%' || st.term || '%'
        OR lower(p.description) ILIKE '%' || st.term || '%'
        OR lower(c.name) ILIKE '%' || st.term || '%'
      )
  )
SELECT id, name, price_in_kes, slug, rank
FROM (
  SELECT id, name, price_in_kes, slug, rank FROM ft_results
  UNION
  SELECT id, name, price_in_kes, slug, rank FROM ilike_results
) AS combined
ORDER BY rank DESC
LIMIT $2
`

type V2SearchProductsParams struct {
	RegexpSplitToTable string
	Limit              int32
}

type V2SearchProductsRow struct {
	ID         uuid.UUID
	Name       string
	PriceInKes int32
	Slug       string
	Rank       float32
}

// Search products using full-text search. This query supports partial matches
// by splitting the input string into tokens and appending the :* operator
// for prefix matching. Matching products are ranked by relevance.
func (q *Queries) V2SearchProducts(ctx context.Context, arg V2SearchProductsParams) ([]V2SearchProductsRow, error) {
	rows, err := q.query(ctx, q.v2SearchProductsStmt, v2SearchProducts, arg.RegexpSplitToTable, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V2SearchProductsRow{}
	for rows.Next() {
		var i V2SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInKes,
			&i.Slug,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const v2SearchProductsCount = `-- name: V2SearchProductsCount :one
WITH
  search_query AS (
    SELECT to_tsquery('english', string_agg(word || ':*', ' & ')) AS query
    FROM regexp_split_to_table($1, '\s+') AS word
  ),
  search_term AS (
    SELECT lower($1) AS term
  ),
  usd_rate AS (
    SELECT rate_to_kes
    FROM exchange_rates
    WHERE currency_code = 'USD'
      AND now() BETWEEN valid_from AND COALESCE(valid_to, now() + interval '100 years')
    ORDER BY valid_from DESC
    LIMIT 1
  ),
  ft_results AS (
    SELECT p.id
    FROM products p
    CROSS JOIN usd_rate ur
    CROSS JOIN search_query sq
    WHERE p.status = 'active'
      AND p.search_keyword @@ sq.query
  ),
  ilike_results AS (
    SELECT DISTINCT p.id
    FROM products p
    CROSS JOIN search_term st
    WHERE p.status = 'active'
      AND (
        lower(p.name) ILIKE '%' || st.term || '%'
        OR lower(p.description) ILIKE '%' || st.term || '%'
      )
  )
SELECT COUNT(*) FROM (
  SELECT id FROM ft_results
  UNION
  SELECT id FROM ilike_results
) AS combined
`

func (q *Queries) V2SearchProductsCount(ctx context.Context, regexpSplitToTable string) (int64, error) {
	row := q.queryRow(ctx, q.v2SearchProductsCountStmt, v2SearchProductsCount, regexpSplitToTable)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const v2SearchProductsPaginated = `-- name: V2SearchProductsPaginated :many
WITH
  search_query AS (
    SELECT to_tsquery('english', string_agg(word || ':*', ' & ')) AS query
    FROM regexp_split_to_table($1, '\s+') AS word
  ),
  search_term AS (
    SELECT lower($1) AS term
  ),
  usd_rate AS (
    SELECT rate_to_kes
    FROM exchange_rates
    WHERE currency_code = 'USD'
      AND now() BETWEEN valid_from AND COALESCE(valid_to, now() + interval '100 years')
    ORDER BY valid_from DESC
    LIMIT 1
  ),
  ft_results AS (
    SELECT
      p.id,
      p.name,
      (p.usd_price * ur.rate_to_kes) AS price_in_kes,
      p.slug,
      ts_rank_cd(p.search_keyword, sq.query) AS rank
    FROM products p
    CROSS JOIN usd_rate ur
    CROSS JOIN search_query sq
    WHERE p.status = 'active'
      AND p.search_keyword @@ sq.query
  ),
  ilike_results AS (
    SELECT DISTINCT
      p.id,
      p.name,
      (p.usd_price * ur.rate_to_kes) AS price_in_kes,
      p.slug,
      0 AS rank
    FROM products p
    CROSS JOIN usd_rate ur
    CROSS JOIN search_term st
    WHERE p.status = 'active'
      AND (
        lower(p.name) ILIKE '%' || st.term || '%'
        OR lower(p.description) ILIKE '%' || st.term || '%'
      )
  )
SELECT id, name, price_in_kes, slug, rank
FROM (
  SELECT id, name, price_in_kes, slug, rank FROM ft_results
  UNION
  SELECT id, name, price_in_kes, slug, rank FROM ilike_results
) AS combined
ORDER BY rank DESC
OFFSET $3 LIMIT $2
`

type V2SearchProductsPaginatedParams struct {
	RegexpSplitToTable string
	Limit              int32
	Offset             int32
}

type V2SearchProductsPaginatedRow struct {
	ID         uuid.UUID
	Name       string
	PriceInKes int32
	Slug       string
	Rank       float32
}

func (q *Queries) V2SearchProductsPaginated(ctx context.Context, arg V2SearchProductsPaginatedParams) ([]V2SearchProductsPaginatedRow, error) {
	rows, err := q.query(ctx, q.v2SearchProductsPaginatedStmt, v2SearchProductsPaginated, arg.RegexpSplitToTable, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V2SearchProductsPaginatedRow{}
	for rows.Next() {
		var i V2SearchProductsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInKes,
			&i.Slug,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
