// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: seo_products.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getProductSEO = `-- name: GetProductSEO :one
SELECT
    p.id,
    p.part_number,
    p.meta_title,
    p.meta_description,
    p.meta_keywords,
    p.usd_price,
    c.name AS brand_name,
    COALESCE(
            (SELECT image_url FROM product_images WHERE product_id = p.id ORDER BY created_at LIMIT 1),
            ''
    )::TEXT AS image_url
FROM products p
         JOIN categories c ON p.category_id = c.id
WHERE p.slug = $1
`

type GetProductSEORow struct {
	ID              uuid.UUID
	PartNumber      string
	MetaTitle       sql.NullString
	MetaDescription sql.NullString
	MetaKeywords    sql.NullString
	UsdPrice        string
	BrandName       string
	ImageUrl        string
}

func (q *Queries) GetProductSEO(ctx context.Context, slug string) (GetProductSEORow, error) {
	row := q.db.QueryRowContext(ctx, getProductSEO, slug)
	var i GetProductSEORow
	err := row.Scan(
		&i.ID,
		&i.PartNumber,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.UsdPrice,
		&i.BrandName,
		&i.ImageUrl,
	)
	return i, err
}

const updateProductSEO = `-- name: UpdateProductSEO :exec
UPDATE products
SET
    part_number = $2,
    meta_title = $3,
    meta_description = $4,
    meta_keywords = $5,
    updated_at = now()
WHERE id = $1
`

type UpdateProductSEOParams struct {
	ID              uuid.UUID
	PartNumber      string
	MetaTitle       sql.NullString
	MetaDescription sql.NullString
	MetaKeywords    sql.NullString
}

func (q *Queries) UpdateProductSEO(ctx context.Context, arg UpdateProductSEOParams) error {
	_, err := q.db.ExecContext(ctx, updateProductSEO,
		arg.ID,
		arg.PartNumber,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
	)
	return err
}
