// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const storeRefreshToken = `-- name: StoreRefreshToken :one
INSERT INTO refresh_tokens (id, user_id, token, created_at, expires_at)
    VALUES (gen_random_uuid(), $1, $2, NOW(), $3)
RETURNING id, user_id, token, created_at, expires_at
`

type StoreRefreshTokenParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
}

type StoreRefreshTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) (StoreRefreshTokenRow, error) {
	row := q.queryRow(ctx, q.storeRefreshTokenStmt, storeRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i StoreRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
