// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countAllUsers = `-- name: CountAllUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, hashed_password, first_name, last_name, phone_number, profile_image_url,
                   date_of_birth, is_active, created_at, updated_at, last_login)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW(),
        NULL) RETURNING id, email, first_name, last_name, phone_number, profile_image_url, date_of_birth, is_active, created_at, updated_at, last_login
`

type CreateUserParams struct {
	Email           string
	HashedPassword  string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
}

type CreateUserRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.HashedPassword,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.ProfileImageUrl,
		arg.DateOfBirth,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfileImageUrl,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active  = FALSE,
    updated_at = NOW()
WHERE id = $1 RETURNING id, email, first_name, last_name, phone_number, profile_image_url, date_of_birth, is_active, created_at, updated_at, last_login
`

type DeactivateUserRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) (DeactivateUserRow, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, id)
	var i DeactivateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfileImageUrl,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,
       email,
       first_name,
       last_name,
       phone_number,
       profile_image_url,
       date_of_birth,
       is_active,
       created_at,
       updated_at,
       last_login
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfileImageUrl,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
       email,
       first_name,
       last_name,
       phone_number,
       profile_image_url,
       date_of_birth,
       is_active,
       created_at,
       updated_at,
       last_login
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfileImageUrl,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id,
       email,
       first_name,
       last_name,
       phone_number,
       profile_image_url,
       date_of_birth,
       is_active,
       created_at,
       updated_at,
       last_login
FROM users
ORDER BY created_at DESC LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.ProfileImageUrl,
			&i.DateOfBirth,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE users
SET last_login = NOW()
WHERE id = $1 RETURNING id, email, first_name, last_name, phone_number, profile_image_url, date_of_birth, is_active, created_at, updated_at, last_login
`

type UpdateUserLastLoginRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) (UpdateUserLastLoginRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserLastLogin, id)
	var i UpdateUserLastLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfileImageUrl,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET hashed_password = $2,
    updated_at      = NOW()
WHERE id = $1 RETURNING id, email, first_name, last_name, phone_number, profile_image_url, date_of_birth, is_active, created_at, updated_at, last_login
`

type UpdateUserPasswordParams struct {
	ID             uuid.UUID
	HashedPassword string
}

type UpdateUserPasswordRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfileImageUrl,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name        = $2,
    last_name         = $3,
    phone_number      = $4,
    profile_image_url = $5,
    date_of_birth     = $6,
    updated_at        = NOW()
WHERE id = $1 RETURNING id, email, first_name, last_name, phone_number, profile_image_url, date_of_birth, is_active, created_at, updated_at, last_login
`

type UpdateUserProfileParams struct {
	ID              uuid.UUID
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
}

type UpdateUserProfileRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.ProfileImageUrl,
		arg.DateOfBirth,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfileImageUrl,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}
