// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_roles.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const assignRoleToUser = `-- name: AssignRoleToUser :one
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
RETURNING id, user_id, role_id, created_at, updated_at
`

type AssignRoleToUserParams struct {
	UserID uuid.NullUUID
	RoleID uuid.NullUUID
}

type AssignRoleToUserRow struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	RoleID    uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (AssignRoleToUserRow, error) {
	row := q.queryRow(ctx, q.assignRoleToUserStmt, assignRoleToUser, arg.UserID, arg.RoleID)
	var i AssignRoleToUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT ur.id, ur.user_id, ur.role_id, r.role_name, ur.created_at, ur.updated_at
FROM user_roles ur
         JOIN roles r ON ur.role_id = r.id
WHERE ur.user_id = $1
`

type GetUserRolesRow struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	RoleID    uuid.NullUUID
	RoleName  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.NullUUID) ([]GetUserRolesRow, error) {
	rows, err := q.query(ctx, q.getUserRolesStmt, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.RoleName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesByUserID = `-- name: GetUserRolesByUserID :many
SELECT r.role_name
FROM roles r
         JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRolesByUserID(ctx context.Context, userID uuid.NullUUID) ([]string, error) {
	rows, err := q.query(ctx, q.getUserRolesByUserIDStmt, getUserRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_name string
		if err := rows.Scan(&role_name); err != nil {
			return nil, err
		}
		items = append(items, role_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT u.id, u.email, u.first_name, u.last_name, u.phone_number, u.profile_image_url, u.date_of_birth, u.is_active, u.created_at, u.updated_at, u.last_login
FROM users u
         JOIN user_roles ur ON u.id = ur.user_id
WHERE ur.role_id = $1
`

type GetUsersByRoleRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       sql.NullString
	LastName        sql.NullString
	PhoneNumber     sql.NullString
	ProfileImageUrl sql.NullString
	DateOfBirth     sql.NullTime
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastLogin       sql.NullTime
}

func (q *Queries) GetUsersByRole(ctx context.Context, roleID uuid.NullUUID) ([]GetUsersByRoleRow, error) {
	rows, err := q.query(ctx, q.getUsersByRoleStmt, getUsersByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByRoleRow{}
	for rows.Next() {
		var i GetUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.ProfileImageUrl,
			&i.DateOfBirth,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllRolesFromUser = `-- name: RemoveAllRolesFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) RemoveAllRolesFromUser(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.exec(ctx, q.removeAllRolesFromUserStmt, removeAllRolesFromUser, userID)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID uuid.NullUUID
	RoleID uuid.NullUUID
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.exec(ctx, q.removeRoleFromUserStmt, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}
