// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: verification_token.sql

package database

import (
	"context"
	"time"
)

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (
    email, token, expires_at
) VALUES (
             $1, $2, $3
         )
RETURNING id, email, token, expires_at, created_at
`

type CreateVerificationTokenParams struct {
	Email     string
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, createVerificationToken, arg.Email, arg.Token, arg.ExpiresAt)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM verification_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokens)
	return err
}

const deleteVerificationTokenByToken = `-- name: DeleteVerificationTokenByToken :exec
DELETE FROM verification_tokens
WHERE token = $1
`

func (q *Queries) DeleteVerificationTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationTokenByToken, token)
	return err
}

const deleteVerificationTokensByEmail = `-- name: DeleteVerificationTokensByEmail :exec
DELETE FROM verification_tokens
WHERE email = $1
`

func (q *Queries) DeleteVerificationTokensByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationTokensByEmail, email)
	return err
}

const getVerificationTokenByEmail = `-- name: GetVerificationTokenByEmail :one
SELECT id, email, token, expires_at, created_at
FROM verification_tokens
WHERE email = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetVerificationTokenByEmail(ctx context.Context, email string) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getVerificationTokenByEmail, email)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationTokenByToken = `-- name: GetVerificationTokenByToken :one
SELECT id, email, token, expires_at, created_at
FROM verification_tokens
WHERE token = $1
`

func (q *Queries) GetVerificationTokenByToken(ctx context.Context, token string) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getVerificationTokenByToken, token)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
