name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            # Change directory to the repository
            cd ${{ github.workspace }}

            # Pull the latest changes from the repository
            git pull origin main

            # Stop running containers and redeploy
            docker-compose down
            docker-compose up -d --build
